#!/bin/sh
# ════════════════════════════════════════════════
# FILE: ci_scripts/ci_post_clone.sh
# ════════════════════════════════════════════════
#
# WHAT THIS DOES (plain language):
#   Prepares an Xcode Cloud machine before it tries to build the iPhone app.
#   Xcode Cloud downloads the code and then immediately looks for the app's
#   building blocks — but half of those live in a folder that is deliberately
#   never stored in the repository, and nothing had ever told the machine to
#   fetch them. So every build failed before it started. This installs them and
#   assembles the web part of the app first.
#
# NOTES / GOTCHAS:
#   - WHY THIS EXISTS. ios/App/CapApp-SPM/Package.swift is generated by the
#     Capacitor CLI and points every plugin at ../../../node_modules/@capacitor/*.
#     node_modules is gitignored (.gitignore:10), and Xcode Cloud resolves Swift
#     packages IMMEDIATELY after cloning — before any build phase could install
#     them. Result, observed 2026-07-28: "Could not resolve package dependencies:
#     the package at '/Volumes/workspace/repository/node_modules/@capacitor/
#     splash-screen' cannot be accessed". ci_post_clone is the one hook that runs
#     early enough to fix it.
#   - Node is NOT preinstalled on Xcode Cloud images. Homebrew is.
#   - Fails LOUDLY on missing Supabase variables rather than producing a bundle
#     with no database address. That failure mode is a blank white screen with a
#     clean console (see the resolveEnvDir comment in vite.config.js), which is
#     far more expensive to diagnose than a failed build.
#   - Duplicated at ios/App/ci_scripts/ci_post_clone.sh, which sources this one.
#     Xcode Cloud looks beside the .xcodeproj OR at the repository root depending
#     on how the workflow resolves its primary repository; a CI script that is
#     silently never found is worse than a redundant four-line shim.
#   - NOT VERIFIED ON XCODE CLOUD by the session that wrote it — it can be run
#     locally (see below) but only a real Xcode Cloud build proves discovery and
#     the image's toolchain. Treat the first green build as the verification.
#
#   Run locally to check the mechanics:
#     CI_PRIMARY_REPOSITORY_PATH="$PWD" sh ci_scripts/ci_post_clone.sh
# ════════════════════════════════════════════════
set -e

# Xcode Cloud sets this; fall back to the repo root relative to this script so
# the same file is runnable by hand.
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$REPO"

echo "ci_post_clone: repository at $REPO"

# ─── Toolchain ──────────────────────────────────────────────────────────────
if ! command -v node > /dev/null 2>&1; then
  echo "ci_post_clone: node not found, installing via Homebrew"
  export HOMEBREW_NO_AUTO_UPDATE=1
  brew install node
fi
echo "ci_post_clone: node $(node --version), npm $(npm --version)"

# ─── Dependencies ───────────────────────────────────────────────────────────
# `npm ci` (not `install`) so the lockfile is authoritative and the build is
# reproducible. This is what creates the node_modules paths Package.swift needs.
npm ci

# ─── Required build-time configuration ──────────────────────────────────────
# Xcode resolves the Capacitor SPM graph immediately after this hook returns.
# Install its node-backed packages before validating Vite configuration, so a
# missing workflow variable cannot be misreported as a missing Swift package.
# Vite inlines these at build time. Absent, the app builds "successfully" and
# then dies on launch while main.jsx is still evaluating its imports.
: "${VITE_SUPABASE_URL:?ci_post_clone: set VITE_SUPABASE_URL in the Xcode Cloud workflow environment}"
: "${VITE_SUPABASE_ANON_KEY:?ci_post_clone: set VITE_SUPABASE_ANON_KEY in the Xcode Cloud workflow environment}"

# Optional, but a TestFlight build almost certainly wants production. Unset means
# the app talks to dev.utahpros.app — deliberate (see src/lib/nativeApiOrigin.js),
# and wrong for a release, so say so rather than let it pass unnoticed.
if [ -z "${VITE_NATIVE_API_ORIGIN:-}" ]; then
  echo "ci_post_clone: WARNING — VITE_NATIVE_API_ORIGIN is unset, so this build"
  echo "ci_post_clone: will send its /api calls to https://dev.utahpros.app."
  echo "ci_post_clone: For a TestFlight/App Store build set it to https://utahpros.app."
else
  echo "ci_post_clone: API origin = $VITE_NATIVE_API_ORIGIN"
fi



# ─── Web bundle ─────────────────────────────────────────────────────────────
# The native target: field/public pages only, with the web-only payload pruned.
node scripts/build-native.mjs

# Copies dist/ into ios/App/App/public and regenerates Package.swift from the
# installed plugins, so the SPM graph matches what npm ci actually produced.
npx cap sync ios

echo "ci_post_clone: ready"
