/**
 * ════════════════════════════════════════════════
 * FILE: qbo-invoice.js
 * ════════════════════════════════════════════════
 *
 * WHAT THIS DOES (plain language):
 *   Executes one ledger-frozen QuickBooks invoice save, send, or delete. The
 *   private command record is written before the provider call so a lost HTTP
 *   response is recovered without creating a second accounting side effect.
 *
 * DEPENDS ON:
 *   Internal: qbo auth, QuickBooks adapter, qbo-invoice-commands, Supabase RPCs
 *   Data: qbo_invoice_commands and the invoice/contact/job source records
 * ════════════════════════════════════════════════
 */

import { handleOptions, jsonResponse } from '../lib/cors.js';
import { authorizeQboBrowserRequest } from '../lib/qbo-auth.js';
import { supabase } from '../lib/supabase.js';
import { getConnection, divisionToQbo, ensureQboCustomer, findClassId, createInvoice, updateInvoice, deleteInvoice, sendInvoice, relinkQboCustomer, isStaleCustomerRef } from '../lib/quickbooks.js';
import { recordReconciliation } from '../lib/qbo-reconciliation.js';
import { mirrorQboInvoiceEmail } from '../lib/qbo-invoice-email-mirror.js';
import { sha256hex } from '../lib/intuit.js';
import { requireQboProviderTraffic, isQboProviderTrafficDisabled } from '../lib/qbo-provider-traffic.js';
import { QBO_COMMAND_ID_RE, finalizeQboInvoiceLineChange, finalizeQboInvoiceLineUpdate, getQboInvoiceCommand, isTerminalQboInvoiceCommand, prepareQboInvoiceCommand, qboCommandActor, qboCommandIdentityMatches, reserveQboInvoiceCommand, releaseQboInvoiceCommandReservation, stageQboInvoiceLineChange, stageQboInvoiceLineUpdate, startQboInvoiceCommandAttempt, advanceQboInvoiceCommandAttempt, setQboInvoiceCommandState, stableJsonStringify } from '../lib/qbo-invoice-commands.js';
import { qboProviderTrafficDisabledRouteResponse, requireQboDocumentCommandV2 } from './qbo-document-command-gate.js';

const MAX_LINE_QUANTITY = 1_000_000;
const MAX_LINE_UNIT_PRICE = 100_000_000;
const MAX_DECIMAL_SOURCE_LENGTH = 128;
const MAX_DECIMAL_EXPONENT = 1_000;

// Convert a finite decimal's source representation into integer units. Do not
// multiply JS floats here: 1.005 and 10.075 are both representable as slightly
// smaller binary values, which would otherwise round a cent down incorrectly.
function decimalParts(value) {
  if ((typeof value !== 'number' && typeof value !== 'string') || String(value).length > MAX_DECIMAL_SOURCE_LENGTH) {
    throw new Error('Money values must be finite decimals.');
  }
  const source = String(value).trim().toLowerCase();
  const match = source.match(/^([+-]?)(\d+)(?:\.(\d+))?(?:e([+-]?\d+))?$/);
  if (!match) throw new Error('Money values must be finite decimals.');
  const exponent = Number(match[4] || 0);
  if (!Number.isSafeInteger(exponent) || Math.abs(exponent) > MAX_DECIMAL_EXPONENT) {
    throw new Error('Money value exponent is outside the supported range.');
  }
  const fraction = match[3] || '';
  let digits = `${match[2]}${fraction}`.replace(/^0+(?=\d)/, '');
  let scale = fraction.length - exponent;
  if (scale < 0) { digits += '0'.repeat(-scale); scale = 0; }
  return { units: BigInt(`${match[1] === '-' ? '-' : ''}${digits || '0'}`), scale };
}

function roundedCents(units, scale) {
  const denominator = 10n ** BigInt(scale);
  const absolute = units < 0n ? -units : units;
  let cents = (absolute * 100n) / denominator;
  // Financial half-up for positive values and half-away-from-zero for credits,
  // matching PostgreSQL numeric round(..., 2) rather than Math.round's negative tie behavior.
  if (((absolute * 100n) % denominator) * 2n >= denominator) cents += 1n;
  return units < 0n ? -cents : cents;
}

function amountFromCents(cents, label = 'Money amount') {
  if (cents > BigInt(Number.MAX_SAFE_INTEGER) || cents < BigInt(Number.MIN_SAFE_INTEGER)) {
    throw new Error(`${label} is outside the supported range.`);
  }
  return Number(cents) / 100;
}

// QBO accepts amounts in cents. The canonical rule is exact decimal
// quantity × unit price, rounded to the nearest cent with half values away
// from zero. This aligns QBO amounts with locally generated numeric totals.
export const round2 = (value) => {
  if (value == null || value === '') return 0;
  const decimal = decimalParts(value);
  return amountFromCents(roundedCents(decimal.units, decimal.scale));
};
// Never trust a carried line_total while composing the frozen provider intent.
// It is generated by Postgres locally and can be stale on an in-memory patch;
// QuickBooks receives the canonical quantity × unit price rounded to cents.
export const qboLineAmount = (li = {}) => {
  if (li.quantity == null || li.unit_price == null) return 0;
  const quantity = decimalParts(li.quantity);
  const unitPrice = decimalParts(li.unit_price);
  const product = quantity.units * unitPrice.units;
  return amountFromCents(roundedCents(product, quantity.scale + unitPrice.scale), 'Line item amount');
};
export const qboFallbackAmount = (inv) => round2(inv.adjusted_total ?? inv.total ?? 0);
const qboDate = (value) => {
  const date = String(value || '').split('T')[0];
  return /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : null;
};
export function qboInvoiceDateFields(inv = {}) {
  const txnDate = qboDate(inv.invoice_date);
  const dueDate = qboDate(inv.due_date) || txnDate;
  return {
    ...(txnDate ? { TxnDate: txnDate } : {}),
    ...(dueDate ? { DueDate: dueDate } : {}),
  };
}

// What the customer actually reads, and who else receives it.  Both are derived
// only from stored invoice columns so a rebuilt intent byte-matches the frozen
// attempt (currentMatchesStoredAttempt); anything non-deterministic here turns
// every retry into a false "invoice changed" conflict.
export function qboSendPresentation(inv = {}, derivedMemo = '') {
  const customerMemo = String(inv.customer_message ?? '').trim() || derivedMemo;
  const cc = String(inv.send_cc_email ?? '').trim();
  return {
    customerMemo,
    // Omitted entirely when empty: sending BillEmailCc with a blank Address
    // would clear a CC the customer's QuickBooks record may legitimately hold.
    billEmailCc: cc ? { BillEmailCc: { Address: cc } } : {},
  };
}

export async function qboInvoiceRequestId(action, invoiceId, clientRequestId, stage = 'primary') {
  const code = { create: 'c', update: 'u', send: 's', delete: 'd' }[action];
  if (!code) throw new Error('Unsupported QBO invoice request action');
  const digest = await sha256hex(JSON.stringify({ action, invoice_id: String(invoiceId), client_request_id: String(clientRequestId), stage: String(stage) }));
  return `upr-i-${code}-${digest.slice(0, 40)}`;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const emailOk = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const rpcObject = (value) => Array.isArray(value) ? value[0] : value;
const definitive = (e) => Number.isFinite(Number(e?.status)) && Number(e.status) >= 400 && Number(e.status) < 500;
const ambiguous = (e) => !Number.isFinite(Number(e?.status)) || Number(e.status) >= 500;
// Provider faults routinely include customer, invoice, and upstream diagnostic
// detail. Persist that detail only in the restricted command ledger; browser
// responses stay stable and safe to replay.
const providerError = (e) => ({
  error: e?.code === 'qbo-realm-mismatch'
    ? 'QuickBooks connection changed accounts; retry the unchanged request.'
    : definitive(e)
      ? 'QuickBooks rejected the invoice request. Review the invoice and try again.'
      : 'Unable to complete the QuickBooks invoice request. Retry the unchanged request.',
  code: e?.code === 'qbo-realm-mismatch' ? 'qbo-realm-mismatch' : definitive(e) ? 'qbo-provider-rejected' : 'qbo-provider-unavailable',
  intuit_tid: e?.intuitTid || null,
  retry_same_request: ambiguous(e),
});
const LINE_UPDATE_FIELDS = Object.freeze(['line_id', 'description', 'qbo_item_id', 'qbo_item_name', 'qbo_class_id', 'qbo_class_name', 'quantity', 'unit_price']);

function lineDecimalFromBody(value, label, maximum) {
  decimalParts(value);
  const numeric = Number(value);
  if (!Number.isFinite(numeric) || Math.abs(numeric) > maximum) {
    throw new Error(`${label} must be a finite decimal within the supported range.`);
  }
  return numeric;
}

function optionalLineText(value, label) {
  if (value == null) return null;
  if (typeof value !== 'string') throw new Error(`${label} must be text.`);
  const text = value.trim();
  return text || null;
}

// Keep the browser payload intentionally narrow. The database repeats every
// validation below; this preflight only prevents a bad request from reserving a
// command before the service-only atomic apply can reject it.
function lineUpdateFromBody(value) {
  if (value == null) return null;
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('line_update must be an object.');
  if (Object.keys(value).some((key) => !LINE_UPDATE_FIELDS.includes(key))) throw new Error('line_update includes an unsupported field.');
  if (!UUID_RE.test(String(value.line_id || ''))) throw new Error('line_update.line_id must be a UUID.');
  if (typeof value.description !== 'string' || !value.description.trim() || value.description.length > 4000) throw new Error('line_update.description is required and must be 4000 characters or fewer.');
  const quantity = lineDecimalFromBody(value.quantity, 'line_update.quantity', MAX_LINE_QUANTITY);
  const unitPrice = lineDecimalFromBody(value.unit_price, 'line_update.unit_price', MAX_LINE_UNIT_PRICE);
  return {
    line_id: String(value.line_id), description: value.description,
    qbo_item_id: optionalLineText(value.qbo_item_id, 'line_update.qbo_item_id'),
    qbo_item_name: optionalLineText(value.qbo_item_name, 'line_update.qbo_item_name'),
    qbo_class_id: optionalLineText(value.qbo_class_id, 'line_update.qbo_class_id'),
    qbo_class_name: optionalLineText(value.qbo_class_name, 'line_update.qbo_class_name'),
    quantity, unit_price: unitPrice,
  };
}

// `line_update` remains the deployed-client compatibility contract. New native
// document screens use `line_change`, which always goes through the same human
// Save-to-QuickBooks command and never writes invoice_line_items from the app.
function lineChangeFromBody(value) {
  if (value == null) return null;
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('line_change must be an object.');
  const kind = value.kind;
  if (!['create', 'update', 'delete', 'reorder'].includes(kind)) throw new Error('line_change.kind is invalid.');
  const patchFields = ['description', 'qbo_item_id', 'qbo_item_name', 'qbo_class_id', 'qbo_class_name', 'quantity', 'unit_price'];
  const cleanPatch = (patch) => {
    if (!patch || typeof patch !== 'object' || Array.isArray(patch) || Object.keys(patch).some((key) => !patchFields.includes(key))) throw new Error('line_change.patch is invalid.');
    if (typeof patch.description !== 'string' || !patch.description.trim() || patch.description.length > 4000) throw new Error('line_change.patch.description is required.');
    const quantity = lineDecimalFromBody(patch.quantity, 'line_change.patch.quantity', MAX_LINE_QUANTITY);
    const unitPrice = lineDecimalFromBody(patch.unit_price, 'line_change.patch.unit_price', MAX_LINE_UNIT_PRICE);
    return { description: patch.description, qbo_item_id: optionalLineText(patch.qbo_item_id, 'line_change.patch.qbo_item_id'), qbo_item_name: optionalLineText(patch.qbo_item_name, 'line_change.patch.qbo_item_name'), qbo_class_id: optionalLineText(patch.qbo_class_id, 'line_change.patch.qbo_class_id'), qbo_class_name: optionalLineText(patch.qbo_class_name, 'line_change.patch.qbo_class_name'), quantity, unit_price: unitPrice };
  };
  if (kind === 'create') {
    if (Object.keys(value).some((key) => !['kind', 'patch', 'sort_order'].includes(key))) throw new Error('line_change includes an unsupported field.');
    if (value.sort_order != null && (!Number.isInteger(value.sort_order) || value.sort_order < 0 || value.sort_order > 2147483647)) throw new Error('line_change.sort_order must be a PostgreSQL integer from 0 through 2147483647.');
    return { kind, patch: cleanPatch(value.patch), ...(value.sort_order == null ? {} : { sort_order: value.sort_order }) };
  }
  if (kind === 'reorder') {
    if (Object.keys(value).some((key) => !['kind', 'ordered_line_ids'].includes(key)) || !Array.isArray(value.ordered_line_ids) || !value.ordered_line_ids.length || new Set(value.ordered_line_ids).size !== value.ordered_line_ids.length || value.ordered_line_ids.some((id) => !UUID_RE.test(String(id)))) throw new Error('line_change.ordered_line_ids must be unique UUIDs.');
    return { kind, ordered_line_ids: value.ordered_line_ids.map(String) };
  }
  if (Object.keys(value).some((key) => !['kind', 'line_id', 'patch'].includes(key)) || !UUID_RE.test(String(value.line_id || ''))) throw new Error('line_change.line_id must be a UUID.');
  return kind === 'update' ? { kind, line_id: String(value.line_id), patch: cleanPatch(value.patch) } : { kind, line_id: String(value.line_id) };
}

// The activity record is evidence, never a gate.  A failure here must not change
// the money outcome the caller already received, so it is swallowed exactly the
// way worker_runs telemetry is -- the durable command ledger remains the source
// of truth for what actually happened.
async function recordActivity(db, { invoiceId, actor, eventType, recipient = null, cc = null, metadata = {} }) {
  try {
    await db.rpc('record_invoice_activity', {
      p_invoice_id: invoiceId,
      p_actor_employee_id: actor?.employeeId || null,
      p_event_type: eventType,
      p_recipient_email: recipient,
      p_cc_email: cc,
      p_safe_metadata: metadata,
    });
  } catch { /* evidence is best-effort; never fail a completed money action */ }
}

async function logRun(db, status, processed, errorMessage, startedAt) {
  try { await db.insert('worker_runs', { worker_name: 'qbo-invoice', status, records_processed: processed, error_message: errorMessage || null, started_at: startedAt, completed_at: new Date().toISOString() }); } catch { /* telemetry must not change money semantics */ }
}

async function reconcile(db, invoiceId, attempted, current, operation) {
  try { await recordReconciliation(db, { entity: 'InvoiceLinkConflict', qboId: `upr:${invoiceId}:operation:${operation}:attempted:${attempted}:current:${current || 'none'}`, reason: 'qbo-invoice-mismatch', context: { upr_invoice_id: invoiceId, operation, attempted_qbo_invoice_id: attempted, current_qbo_invoice_id: current || 'none' } }); } catch { /* durable command remains the source of truth */ }
}

function replay(command, request, env) {
  return jsonResponse(command.response_payload || { error: command.error || 'QuickBooks invoice command did not retain a response' }, Number(command.response_status) || (command.status === 'succeeded' ? 200 : 500), request, env);
}

// The terminal state transition normally deletes its reservation atomically in
// SQL. Exact patched replays deliberately reacquire that fence, so replay is
// safe to return only after cleanup is confirmed; otherwise the browser must
// retain the same operation id to recover the stranded reservation.
async function replayTerminal(db, command, request, env) {
  const retry = await releasePreProviderReservation(db, {
    commandId: command.id,
    invoiceId: command.invoice_id,
  }, request, env);
  if (retry) return retry;
  return replay(command, request, env);
}

// A known pre-provider rejection is definitive only after its exact reservation
// is durably gone. If cleanup is unavailable, preserve both the database fence
// and the browser's content-bound operation id so the same request can recover.
async function releasePreProviderReservation(db, { commandId, invoiceId }, request, env) {
  try {
    const released = await releaseQboInvoiceCommandReservation(db, { commandId, invoiceId });
    if (released?.ok === true) return null;
  } catch {
    // The retry response below is the safety outcome for an unknown release.
  }
  return jsonResponse({
    error: 'QuickBooks command cleanup did not complete. Retry the same request.',
    code: 'reservation-release-failed',
    retry_same_request: true,
  }, 503, request, env);
}

async function finalize(db, commandId, status, responseStatus, responsePayload, error = null, providerResult = null, intuitRequestId = null) {
  await setQboInvoiceCommandState(db, { commandId, status, providerResult, responseStatus, responsePayload, error, intuitRequestId });
}

async function needsReconciliation(db, command, request, env, message, current = null) {
  const payload = { error: message, code: 'qbo-invoice-mismatch', current_qbo_invoice_id: current || null, retry_same_request: true };
  await finalize(db, command.id, 'needs_reconciliation', 409, payload, message);
  await reconcile(db, command.invoice_id, command.target_qbo_invoice_id || command.provider_result?.qbo_invoice_id || 'none', current, command.action);
  return jsonResponse(payload, 409, request, env);
}

// QBO has already accepted a side effect when this helper is used.  Never let
// a later ledger/CAS/finalization error make the browser retire its operation
// id: the stored provider request id is the only safe retry identity.
async function postProviderFailure(db, command, request, env) {
  const payload = {
    error: 'QuickBooks may have accepted this request, but local finalization did not complete. Retry the same request.',
    code: 'post-provider-finalization-failed',
    retry_same_request: true,
  };
  try {
    await setQboInvoiceCommandState(db, {
      commandId: command.id,
      status: 'ambiguous',
      responseStatus: 500,
      responsePayload: payload,
      error: payload.error,
    });
  } catch {
    // provider_started already durably holds the exact QBO request id; the
    // browser signal below preserves its matching client operation id too.
  }
  return jsonResponse(payload, 500, request, env);
}

// A timeout from QBO is already an unknown side-effect outcome.  The response
// must retain the client operation id even when recording that ambiguity fails.
async function ambiguousProviderFailure(db, command, error, request, env) {
  // The shared adapter rechecks the maintenance gate immediately before each
  // Intuit request. A close at that point means this attempt did not make that
  // particular provider call, but provider_started still owns the frozen
  // request identity (a prior stage may have succeeded). Keep it durable and
  // give the browser the stable maintenance response rather than a generic 500.
  const maintenanceDenied = isQboProviderTrafficDisabled(error);
  const payload = maintenanceDenied
    ? { error: 'QuickBooks provider traffic is temporarily disabled.', code: 'qbo_provider_traffic_disabled', reason: 'qbo_provider_traffic_disabled', retry_same_request: true }
    : providerError(error);
  try {
    await setQboInvoiceCommandState(db, {
      commandId: command.id,
      status: 'ambiguous',
      responseStatus: maintenanceDenied ? 503 : 500,
      responsePayload: payload,
      error: error.message,
      intuitRequestId: error.intuitTid || null,
    });
  } catch {
    // The pre-provider_started row still freezes the QBO request id.  The
    // retry_same_request response keeps its matching browser operation id.
  }
  return jsonResponse(payload, maintenanceDenied ? 503 : 500, request, env);
}

function withFrozenLinePatch(items, frozenLineUpdate) {
  if (!frozenLineUpdate) return items;
  return items.map((item) => (
    String(item.id) === String(frozenLineUpdate.line_id)
      ? { ...item, ...frozenLineUpdate.patch }
      : item
  ));
}

function withFrozenLineChange(items, frozenChange) {
  if (!frozenChange) return items;
  const kind = frozenChange.kind;
  if (kind === 'update') return withFrozenLinePatch(items, { line_id: frozenChange.line_id, patch: frozenChange.patch });
  if (kind === 'create') {
    const candidate = { id: frozenChange.line_id, ...frozenChange.patch, sort_order: frozenChange.sort_order ?? items.length };
    const current = items.find((item) => String(item.id) === String(frozenChange.line_id));
    const exact = current
      && ['description', 'qbo_item_id', 'qbo_item_name', 'qbo_class_id', 'qbo_class_name', 'quantity', 'unit_price', 'sort_order']
        .every((field) => (current[field] ?? null) === (candidate[field] ?? null));
    // Crash recovery after local finalization must rebuild the same one-line
    // provider candidate, not append the frozen create a second time.
    if (exact) return items;
    return [...items, candidate].sort((a, b) => Number(a.sort_order ?? 0) - Number(b.sort_order ?? 0));
  }
  if (kind === 'delete') return items.filter((item) => String(item.id) !== String(frozenChange.line_id));
  if (kind === 'reorder') {
    const index = new Map(frozenChange.ordered_line_ids.map((id, i) => [String(id), i]));
    return items.map((item) => ({ ...item, sort_order: index.get(String(item.id)) })).sort((a, b) => a.sort_order - b.sort_order);
  }
  return items;
}

function requestedLineUpdateMatchesCommand(command, lineUpdate, lineChange = null) {
  const storedChange = command?.intent_payload?.line_change || null;
  if (lineChange) return storedChange && stableJsonStringify(storedChange.request || storedChange) === stableJsonStringify(lineChange);
  if (storedChange) return false;
  const stored = command?.intent_payload?.line_update || null;
  if (!stored && !lineUpdate) return true;
  if (!stored || !lineUpdate) return false;
  const requestedPatch = Object.fromEntries(
    Object.entries(lineUpdate).filter(([key]) => key !== 'line_id'),
  );
  return String(stored.line_id) === String(lineUpdate.line_id)
    && stableJsonStringify(stored.patch) === stableJsonStringify(requestedPatch);
}

async function buildSaveIntent(db, env, request, inv, frozenLineUpdate = null, frozenLineChange = null, expectedRealmId = null) {
  const job = (await db.select('jobs', `id=eq.${inv.job_id}&select=division,job_number,claim_id,address,city,state,zip,date_of_loss&limit=1`))?.[0];
  if (!job) throw new Error('Job not found for invoice');
  let contact = inv.contact_id ? (await db.select('contacts', `id=eq.${inv.contact_id}&select=qbo_customer_id,name&limit=1`))?.[0] : null;
  if (!contact?.qbo_customer_id && inv.contact_id) {
    // This server-to-server self-heal intentionally happens only after the
    // durable invoice reservation. ensureQboCustomer is best-effort and masks
    // timeouts as false, so a missing mapping after an attempt is ambiguous:
    // retain the reservation and require the same command id on retry.
    const ensured = await ensureQboCustomer(request, env, inv.contact_id, { expectedRealmId });
    contact = (await db.select('contacts', `id=eq.${inv.contact_id}&select=qbo_customer_id,name&limit=1`))?.[0] || contact;
    if (!contact?.qbo_customer_id) {
      const error = new Error(ensured
        ? 'QuickBooks customer sync did not finish; retry this same invoice action.'
        : 'QuickBooks customer sync outcome is unknown; retry this same invoice action.');
      error.qboReservationRetained = true;
      throw error;
    }
  }
  if (!contact?.qbo_customer_id) throw new Error('Invoice contact has no QuickBooks customer — sync the client first');
  const map = divisionToQbo(job.division);
  if (!map) throw new Error(`No QuickBooks mapping for division "${job.division}"`);
  const claim = job.claim_id ? (await db.select('claims', `id=eq.${job.claim_id}&select=claim_number,date_of_loss,loss_address,loss_city,loss_state,loss_zip&limit=1`))?.[0] || null : null;
  const sourceItems = await db.select('invoice_line_items', `invoice_id=eq.${inv.id}&order=sort_order.asc.nullslast,created_at.asc`) || [];
  const items = withFrozenLineChange(withFrozenLinePatch(sourceItems, frozenLineUpdate), frozenLineChange);
  const lines = items.length ? items.map((li) => {
    const detail = { ItemRef: { value: String(li.qbo_item_id || map.itemId) } };
    if (li.qbo_class_id) detail.ClassRef = { value: String(li.qbo_class_id) };
    if (li.quantity != null) detail.Qty = Number(li.quantity); if (li.unit_price != null) detail.UnitPrice = Number(li.unit_price);
    return { DetailType: 'SalesItemLineDetail', Amount: qboLineAmount(li), ...(li.description ? { Description: li.description } : {}), SalesItemLineDetail: detail };
  }) : [{ DetailType: 'SalesItemLineDetail', Amount: qboFallbackAmount(inv), SalesItemLineDetail: { ItemRef: { value: String(map.itemId) } } }];
  if (!(lines.reduce((sum, line) => sum + Number(line.Amount || 0), 0) > 0)) throw new Error('Invoice total is 0 — add a line item with an amount before syncing');
  const fmt = (d) => { const p = String(d || '').split('T')[0].split('-'); return p.length === 3 ? `${+p[1]}/${+p[2]}/${p[0]}` : ''; };
  const address = [job.address || claim?.loss_address, job.city || claim?.loss_city, job.state || claim?.loss_state, job.zip || claim?.loss_zip].filter(Boolean).join(', ');
  const memo = `Date of loss: ${fmt(job.date_of_loss || claim?.date_of_loss)} · Job: ${job.job_number || ''} · Claim: ${inv.claim_number || claim?.claim_number || ''} · Service Address: ${address}`;
  let docNumber = inv.qbo_doc_number || null;
  if (!docNumber && job.job_number) { const siblings = await db.select('invoices', `job_id=eq.${inv.job_id}&select=id,created_at&order=created_at.asc,id.asc`) || []; const pos = siblings.findIndex((row) => row.id === inv.id); const suffix = pos > 0 ? `-${pos + 1}` : ''; docNumber = String(job.job_number).slice(0, 21 - suffix.length) + suffix; }
  const shipAddr = Object.fromEntries(Object.entries({ Line1: job.address || claim?.loss_address || null, City: job.city || claim?.loss_city || null, CountrySubDivisionCode: job.state || claim?.loss_state || null, PostalCode: job.zip || claim?.loss_zip || null }).filter(([, value]) => value));
  let linkedTxn = null;
  if (inv.estimate_id) { const estimate = (await db.select('estimates', `id=eq.${inv.estimate_id}&select=qbo_estimate_id&limit=1`))?.[0]; if (estimate?.qbo_estimate_id) linkedTxn = [{ TxnId: String(estimate.qbo_estimate_id), TxnType: 'Estimate' }]; }
  const payCfg = await db.select('integration_config', 'key=in.(accept_card,accept_ach)&select=key,value') || [];
  const onlinePay = Object.fromEntries([['AllowOnlineCreditCardPayment', 'accept_card'], ['AllowOnlineACHPayment', 'accept_ach']].filter(([, key]) => payCfg.find((row) => row.key === key)?.value === 'true').map(([field]) => [field, true]));
  // PrivateNote keeps the derived job/claim/loss context for internal QuickBooks
  // use; CustomerMemo is what the customer reads.  QuickBooks has no CC on its
  // send endpoint, so BillEmailCc must already be on the invoice when the send
  // fires -- the existing save-then-send pair carries it with no extra provider
  // effect per command.
  const { customerMemo, billEmailCc } = qboSendPresentation(inv, memo);
  const shared = { Line: lines, ...qboInvoiceDateFields(inv), PrivateNote: memo, CustomerMemo: { value: customerMemo }, ...billEmailCc, ...(docNumber ? { DocNumber: docNumber } : {}), ...(Object.keys(shipAddr).length ? { ShipAddr: shipAddr } : {}), ...(linkedTxn ? { LinkedTxn: linkedTxn } : {}), ...onlinePay };
  const action = inv.qbo_invoice_id ? 'update' : 'create';
  const payload = inv.qbo_invoice_id ? shared : { CustomerRef: { value: String(contact.qbo_customer_id) }, ...shared };
  // Fallback payloads are frozen now; they are selected only after a definitive 4xx.
  return { action: 'save', expected_qbo_invoice_id: inv.qbo_invoice_id == null ? null : String(inv.qbo_invoice_id), target_qbo_invoice_id: inv.qbo_invoice_id == null ? null : String(inv.qbo_invoice_id), provider_action: action, default_class_name: map.className || null, primary_payload: payload, without_online_pay_payload: Object.keys(onlinePay).length ? (() => { const { AllowOnlineCreditCardPayment, AllowOnlineACHPayment, ...rest } = payload; return rest; })() : null, without_doc_number_payload: docNumber ? (() => { const { DocNumber, ...rest } = payload; return rest; })() : null, customer_relink_contact_id: !inv.qbo_invoice_id ? inv.contact_id || null : null };
}

async function currentIntent(db, env, request, action, inv, body, frozenLineUpdate = null, frozenLineChange = null, expectedRealmId = null) {
  if (action === 'delete') return { action, expected_qbo_invoice_id: inv.qbo_invoice_id == null ? null : String(inv.qbo_invoice_id), target_qbo_invoice_id: inv.qbo_invoice_id == null ? null : String(inv.qbo_invoice_id), provider_action: 'delete', primary_payload: { missing_is_success: true } };
  if (action === 'send') {
    let recipient = String(body.send_to || '').trim();
    if (!recipient && inv.contact_id) recipient = String((await db.select('contacts', `id=eq.${inv.contact_id}&select=email&limit=1`))?.[0]?.email || '').trim();
    if (!inv.qbo_invoice_id) throw new Error('Invoice has not been sent to QuickBooks yet — push it first, then email.');
    if (!recipient) throw new Error('No email address on file for this customer — add one to the contact (or pass send_to) before emailing.');
    if (!emailOk(recipient)) throw new Error(`Customer email looks invalid: ${recipient}`);
    return { action, expected_qbo_invoice_id: String(inv.qbo_invoice_id), target_qbo_invoice_id: String(inv.qbo_invoice_id), recipient, provider_action: 'send', primary_payload: { recipient } };
  }
  return buildSaveIntent(db, env, request, inv, frozenLineUpdate, frozenLineChange, expectedRealmId);
}

function attemptFromIntent(intent, invoiceId, clientRequestId, stage = 'primary') {
  const providerAction = intent.provider_action;
  return qboInvoiceRequestId(providerAction, invoiceId, clientRequestId, stage).then((providerRequestId) => ({ stage, providerAction, providerTargetId: intent.target_qbo_invoice_id, providerRequestId, providerPayload: intent.primary_payload }));
}

async function executeProvider(env, attempt, command) {
  const expectedRealmId = String(command.realm_id);
  if (attempt.providerAction === 'create') return createInvoice(env, attempt.providerPayload, { requestId: attempt.providerRequestId, expectedRealmId });
  if (attempt.providerAction === 'update') return updateInvoice(env, attempt.providerTargetId, attempt.providerPayload, { requestId: attempt.providerRequestId, expectedRealmId });
  if (attempt.providerAction === 'send') return sendInvoice(env, attempt.providerTargetId, attempt.providerPayload.recipient, { requestId: attempt.providerRequestId, expectedRealmId });
  return deleteInvoice(env, attempt.providerTargetId, { requestId: attempt.providerRequestId, expectedRealmId, missingIsSuccess: true });
}

function stagedSavePayload(intent, command) {
  const stage = command.provider_stage || 'primary';
  let payload = intent.primary_payload;
  if (stage === 'without-online-pay') payload = intent.without_online_pay_payload;
  if (stage === 'without-doc-number') payload = intent.without_doc_number_payload;
  if (stage === 'customer-relinked') payload = { ...payload, CustomerRef: command.provider_payload?.CustomerRef };
  return payload;
}

function fillMissingClassRefs(payload, classId) {
  if (!classId || !Array.isArray(payload?.Line)) return payload;
  return {
    ...payload,
    Line: payload.Line.map((line) => {
      if (line?.DetailType !== 'SalesItemLineDetail' || line.SalesItemLineDetail?.ClassRef) return line;
      return { ...line, SalesItemLineDetail: { ...line.SalesItemLineDetail, ClassRef: { value: String(classId) } } };
    }),
  };
}

function alignLocalClassesWithStored(localPayload, storedPayload) {
  if (!Array.isArray(localPayload?.Line) || !Array.isArray(storedPayload?.Line)) return localPayload;
  return {
    ...localPayload,
    Line: localPayload.Line.map((line, index) => {
      const storedClass = storedPayload.Line[index]?.SalesItemLineDetail?.ClassRef;
      if (line?.SalesItemLineDetail?.ClassRef || !storedClass) return line;
      return { ...line, SalesItemLineDetail: { ...line.SalesItemLineDetail, ClassRef: storedClass } };
    }),
  };
}

async function currentMatchesStoredAttempt(db, env, request, command, inv, body) {
  if (command.action === 'delete') return inv.qbo_invoice_id == null || String(inv.qbo_invoice_id) === String(command.expected_qbo_invoice_id);
  if (command.action === 'send') {
    const current = await currentIntent(db, env, request, 'send', inv, body, null, null, command.realm_id);
    return String(inv.qbo_invoice_id || '') === String(command.target_qbo_invoice_id || '') && current.recipient === command.intent_payload.recipient;
  }
  // Freeze create/update selection to the command's pre-provider link.  A
  // successful CAS may have changed the live link from null to the created QBO
  // id; that is proof of completion, not an invoice edit.
  const frozen = { ...inv, qbo_invoice_id: command.expected_qbo_invoice_id, qbo_doc_number: command.intent_payload?.primary_payload?.DocNumber || null };
  const rebuilt = await buildSaveIntent(db, env, request, frozen, command.intent_payload?.line_update || null, command.intent_payload?.line_change || null, command.realm_id);
  const stored = command.provider_payload || stagedSavePayload(command.intent_payload, command);
  const local = alignLocalClassesWithStored(stagedSavePayload(rebuilt, command), stored);
  return stableJsonStringify(local) === stableJsonStringify(stored);
}

export async function onRequestOptions(context) { return handleOptions(context.request, context.env); }

export async function onRequestPost(context) {
  const { request, env } = context; const startedAt = new Date().toISOString(); const db = supabase(env);
  // Invoice writes are a human Save-to-QuickBooks action.  Unlike the
  // background-safe QBO workers, they never accept the shared webhook secret.
  const auth = await authorizeQboBrowserRequest(request, env, db); if (!auth.ok) return jsonResponse({ error: auth.error }, auth.status, request, env);
  const commandId = (request.headers.get('Idempotency-Key') || '').trim();
  if (!QBO_COMMAND_ID_RE.test(commandId)) return jsonResponse({ error: 'A UUIDv4 Idempotency-Key is required for QuickBooks invoice actions' }, 400, request, env);
  let body = {}; try { body = await request.json(); } catch { /* handled below */ }
  const invoiceId = body.invoice_id; if (!invoiceId) return jsonResponse({ error: 'Provide invoice_id' }, 400, request, env);
  if (!UUID_RE.test(String(invoiceId))) return jsonResponse({ error: 'invoice_id must be a UUID' }, 400, request, env);
  const action = ['send', 'delete'].includes(body.action) ? body.action : 'save';
  let lineUpdate; let lineChange;
  try {
    lineUpdate = lineUpdateFromBody(body.line_update);
    lineChange = lineChangeFromBody(body.line_change);
    if (lineUpdate && lineChange) throw new Error('Provide either line_update or line_change, not both.');
    if ((lineUpdate || lineChange) && action !== 'save') throw new Error('Line changes are only valid with a save action.');
  } catch (error) {
    return jsonResponse({ error: error.message }, 400, request, env);
  }
  if ((lineUpdate || lineChange) && !(await requireQboDocumentCommandV2(db))) {
    return jsonResponse({ error: 'QuickBooks document commands are temporarily unavailable.', code: 'qbo_document_command_v2_disabled' }, 503, request, env);
  }
  try { await requireQboProviderTraffic(env); } catch (error) {
    if (isQboProviderTrafficDisabled(error)) return qboProviderTrafficDisabledRouteResponse(request, env);
    throw error;
  }
  // Connection is read-only local configuration. Keep it before the private
  // ledger lookup so a disconnected account preserves the historical 409
  // contract without writing a reservation that needs later cleanup.
  const conn = await getConnection(env); if (!conn?.refresh_token || !conn.realm_id) return jsonResponse({ error: 'QuickBooks not connected' }, 409, request, env);
  const actor = qboCommandActor(auth); const realmId = String(conn.realm_id);
  const existing = await getQboInvoiceCommand(db, commandId);
  const existingTerminal = isTerminalQboInvoiceCommand(existing);
  if (existing?.ok) {
    if (!qboCommandIdentityMatches(existing, { invoiceId, action, actor, realmId })) return jsonResponse({ error: 'Idempotency-Key belongs to a different invoice, action, account, or QuickBooks realm' }, 409, request, env);
    if (!requestedLineUpdateMatchesCommand(existing, lineUpdate, lineChange)) return jsonResponse({ error: 'Idempotency-Key belongs to a different invoice line operation.', code: lineChange ? 'line-change-mismatch' : 'line-update-mismatch', retry_same_request: true }, 409, request, env);
    // A terminal command normally has no reservation. A retry that carries a
    // line patch reacquires its exact, terminal command fence below so the
    // atomic function can prove the patch still equals the stored line before
    // replaying a prior success.
    if (existingTerminal && !existing.intent_payload?.line_update && !existing.intent_payload?.line_change) return replayTerminal(db, existing, request, env);
  }
  // This RPC locks the invoice row, refuses a manual lock, and commits a durable
  // same-command-only reservation before any intent build can self-heal a QBO
  // customer. The lock trigger uses the same parent row, closing the stale-read
  // race between a manual lock and an outbound accounting request.
  const reservation = await reserveQboInvoiceCommand(db, { commandId, invoiceId, action, actor, realmId });
  if (!reservation?.ok) {
    if (reservation?.reason === 'invoice-locked') return jsonResponse({ error: 'Invoice is locked' }, 423, request, env);
    if (reservation?.reason === 'invoice-not-found') return jsonResponse({ error: 'Invoice not found' }, 404, request, env);
    return jsonResponse({ error: 'QuickBooks command requires review before retrying.', code: reservation?.reason || 'command-conflict' }, 409, request, env);
  }
  const inv = (await db.select('invoices', `id=eq.${invoiceId}&limit=1`))?.[0];
  if (!inv) {
    // Defensive only: reserve_qbo_invoice_command has already locked/proved the
    // parent exists. If a read replica nevertheless cannot return it, this is a
    // known no-provider failure and must not strand the manual lock boundary.
    const retry = await releasePreProviderReservation(db, { commandId, invoiceId }, request, env);
    if (retry) return retry;
    return jsonResponse({ error: 'Invoice not found' }, 404, request, env);
  }
  let frozenLineUpdate = null;
  let frozenLineChange = null;
  if (lineUpdate) {
    const staged = await stageQboInvoiceLineUpdate(db, {
      commandId, invoiceId, actor, realmId, lineUpdate,
    });
    if (!staged?.ok) {
      // Before a command exists, validation/staging failures are known local
      // rejections. Existing nonterminal commands keep their reservation.
      if (!existing?.ok || existingTerminal) {
        const retry = await releasePreProviderReservation(db, { commandId, invoiceId }, request, env);
        if (retry) return retry;
      }
      if (staged?.reason === 'invoice-locked') return jsonResponse({ error: 'Invoice is locked' }, 423, request, env);
      const status = ['patch-conflict', 'source-mismatch', 'reservation-mismatch', 'command-mismatch'].includes(staged?.reason) ? 409 : 400;
      return jsonResponse({ error: staged?.error || 'Invoice line update could not be staged.', code: staged?.reason || 'line-update-failed', ...((existing?.ok && !existingTerminal) ? { retry_same_request: true } : {}) }, status, request, env);
    }
    frozenLineUpdate = staged.line_update;
    if (existingTerminal) return replayTerminal(db, existing, request, env);
  }
  if (lineChange) {
    let staged;
    try {
      staged = await stageQboInvoiceLineChange(db, { commandId, invoiceId, actor, realmId, lineChange });
    } catch {
      // Staging is pre-provider and non-mutating. A new/terminal command can
      // safely release its reservation; an existing nonterminal command must
      // retain the fence and exact retry identity for review.
      if (!existing?.ok || existingTerminal) {
        const retry = await releasePreProviderReservation(db, { commandId, invoiceId }, request, env);
        if (retry) return retry;
      }
      return jsonResponse({
        error: 'Invoice line operation could not be staged.',
        code: 'line-change-staging-failed',
        ...((existing?.ok && !existingTerminal) ? { retry_same_request: true } : {}),
      }, 400, request, env);
    }
    if (!staged?.ok) {
      if (!existing?.ok || existingTerminal) {
        const retry = await releasePreProviderReservation(db, { commandId, invoiceId }, request, env);
        if (retry) return retry;
      }
      const status = ['source-mismatch', 'change-conflict', 'reservation-mismatch', 'command-mismatch'].includes(staged?.reason) ? 409 : 400;
      return jsonResponse({ error: staged?.error || 'Invoice line operation could not be staged.', code: staged?.reason || 'line-change-failed', ...((existing?.ok && !existingTerminal) ? { retry_same_request: true } : {}) }, status, request, env);
    }
    frozenLineChange = staged.line_change;
    if (existingTerminal) return replayTerminal(db, existing, request, env);
  }
  // A same-key retry after the request was started must never silently use a
  // newly edited invoice, recipient, or QBO link.  Keep the stored attempt
  // authoritative when unchanged; otherwise return a durable review response
  // before touching QBO.
  if (existing?.ok && ['provider_started', 'ambiguous', 'provider_succeeded'].includes(existing.status)) {
    let unchanged = false;
    try { unchanged = await currentMatchesStoredAttempt(db, env, request, existing, inv, body); } catch { unchanged = false; }
    if (!unchanged) {
      const payload = { error: 'Invoice changed after this QuickBooks command started; reload and review before retrying.', code: 'command-source-mismatch', retry_same_request: true };
      if (existing.status === 'provider_started') {
        await setQboInvoiceCommandState(db, { commandId: existing.id, status: 'ambiguous', responseStatus: 409, responsePayload: payload, error: payload.error });
        await setQboInvoiceCommandState(db, { commandId: existing.id, status: 'needs_reconciliation', responseStatus: 409, responsePayload: payload, error: payload.error });
      }
      else if (existing.status === 'ambiguous') await setQboInvoiceCommandState(db, { commandId: existing.id, status: 'needs_reconciliation', responseStatus: 409, responsePayload: payload, error: payload.error });
      else await setQboInvoiceCommandState(db, { commandId: existing.id, status: 'needs_reconciliation', responseStatus: 409, responsePayload: payload, error: payload.error });
      await reconcile(db, existing.invoice_id, existing.target_qbo_invoice_id || existing.provider_result?.qbo_invoice_id || 'none', inv.qbo_invoice_id || null, existing.action);
      return jsonResponse(payload, 409, request, env);
    }
  }
  let intent;
  try {
    intent = await currentIntent(db, env, request, action, inv, body, frozenLineUpdate, frozenLineChange, realmId);
    if (frozenLineUpdate) intent = { ...intent, line_update: frozenLineUpdate };
    if (frozenLineChange) intent = { ...intent, line_change: frozenLineChange };
  } catch (e) {
    // A customer create can have reached QBO even when its worker response was
    // lost. Keep the reservation in that one ambiguous case; all known-local
    // validation failures are safe to release before a ledger command exists.
    if (e?.qboReservationRetained) {
      return jsonResponse({ error: e.message, retry_same_request: true }, 503, request, env);
    }
    if (!existing?.ok) {
      const retry = await releasePreProviderReservation(db, { commandId, invoiceId }, request, env);
      if (retry) return retry;
    }
    return jsonResponse({ error: e.message, ...(existing?.ok ? { retry_same_request: true } : {}) }, 400, request, env);
  }
  let command;
  // Once QBO has succeeded, the frozen command (not a source rebuilt after
  // CAS) owns finalization.  This is the post-CAS crash-recovery path.
  if (existing?.ok && existing.status === 'provider_succeeded') command = existing;
  else {
    const prepared = await prepareQboInvoiceCommand(db, { commandId, invoiceId, action, actor, realmId, expectedQboInvoiceId: intent.expected_qbo_invoice_id, targetQboInvoiceId: intent.target_qbo_invoice_id, intent });
    if (!prepared?.ok) {
      if (!existing?.ok) {
        const retry = await releasePreProviderReservation(db, { commandId, invoiceId }, request, env);
        if (retry) return retry;
      }
      return jsonResponse({ error: 'QuickBooks command requires review before retrying.', code: prepared?.reason || 'command-conflict', ...(existing?.ok ? { retry_same_request: true } : {}) }, 409, request, env);
    }
    command = await getQboInvoiceCommand(db, prepared.command_id || commandId);
  }
  if (!command?.ok || !qboCommandIdentityMatches(command, { invoiceId, action, actor, realmId })) return jsonResponse({ error: 'QuickBooks command identity could not be verified' }, 409, request, env);
  if (isTerminalQboInvoiceCommand(command)) return replayTerminal(db, command, request, env);
  if (command.status === 'needs_reconciliation') return replay(command, request, env);
  let providerResult = command.provider_result;
  // A delete of an already-unlinked invoice is a local idempotent completion.
  // It still flows through the ledger and CAS, but never manufactures a null
  // provider target or calls QBO.
  if (action === 'delete' && command.status === 'prepared' && command.expected_qbo_invoice_id == null) {
    await setQboInvoiceCommandState(db, { commandId: command.id, status: 'succeeded', responseStatus: 200, responsePayload: { deleted: null, idempotent: true } });
    return replayTerminal(db, await getQboInvoiceCommand(db, command.id), request, env);
  }
  if (command.status !== 'provider_succeeded') {
    let attempt;
    if (command.status === 'prepared') {
      let providerPayload = command.intent_payload.primary_payload;
      if (command.action === 'save' && command.intent_payload.default_class_name) {
        let defaultClassId;
        try {
          defaultClassId = await findClassId(env, command.intent_payload.default_class_name, { expectedRealmId: String(command.realm_id) });
        } catch (error) {
          const status = error?.code === 'qbo-realm-mismatch' ? 409 : 500;
          await finalize(db, command.id, 'rejected', status, providerError(error), error.message, null, error.intuitTid || null);
          return jsonResponse(providerError(error), status, request, env);
        }
        if (!defaultClassId) {
          const payload = { error: `QuickBooks class "${command.intent_payload.default_class_name}" is not available; sync the class catalog and retry.` };
          await finalize(db, command.id, 'rejected', 409, payload, payload.error);
          return jsonResponse(payload, 409, request, env);
        }
        providerPayload = fillMissingClassRefs(providerPayload, defaultClassId);
      }
      attempt = { ...(await attemptFromIntent(command.intent_payload, command.invoice_id, command.id)), providerPayload };
      const started = await startQboInvoiceCommandAttempt(db, { commandId: command.id, ...attempt });
      if (!started?.ok) return jsonResponse({ error: 'QuickBooks command attempt could not be started', code: started?.reason }, 409, request, env);
      attempt = { stage: started.provider_stage, providerAction: started.provider_action, providerTargetId: started.provider_target_id, providerRequestId: started.provider_request_id, providerPayload: started.provider_payload };
    } else {
      attempt = { stage: command.provider_stage, providerAction: command.provider_action, providerTargetId: command.provider_target_id, providerRequestId: command.provider_request_id, providerPayload: command.provider_payload };
    }
    try {
      providerResult = await executeProvider(env, attempt, command);
    } catch (e) {
      if (ambiguous(e)) return ambiguousProviderFailure(db, command, e, request, env);
      // A fallback is permitted only after a definitive 4xx and becomes a new frozen attempt.
      let fallback = null;
      if (action === 'save' && command.intent_payload.without_online_pay_payload && /payment|online|merchant/i.test(e.message || '')) {
        const { AllowOnlineCreditCardPayment, AllowOnlineACHPayment, ...payload } = attempt.providerPayload;
        fallback = { stage: 'without-online-pay', payload };
      }
      if (action === 'save' && !fallback && command.intent_payload.without_doc_number_payload && (e.qboCode === '6140' || /duplicate document number/i.test(e.message || ''))) {
        const { DocNumber, ...payload } = attempt.providerPayload;
        fallback = { stage: 'without-doc-number', payload };
      }
      if (action === 'save' && !fallback && command.intent_payload.customer_relink_contact_id && isStaleCustomerRef(e)) {
        try {
          const relink = await relinkQboCustomer(env, db, command.intent_payload.customer_relink_contact_id, { expectedRealmId: String(command.realm_id) });
          const payload = { ...attempt.providerPayload, CustomerRef: { value: String(relink.id) } }; fallback = { stage: 'customer-relinked', payload, customerRelink: `QuickBooks customer was re-linked automatically (matched by ${relink.matchedBy}).` };
        } catch (relinkError) {
          if (ambiguous(relinkError)) return ambiguousProviderFailure(db, command, relinkError, request, env);
          const status = relinkError?.code === 'qbo-realm-mismatch' ? 409 : 500;
          await finalize(db, command.id, 'rejected', status, providerError(relinkError), relinkError.message, null, relinkError.intuitTid || null);
          return jsonResponse(providerError(relinkError), status, request, env);
        }
      }
      if (!definitive(e) || !fallback) { const status = e?.code === 'qbo-realm-mismatch' ? 409 : 500; await finalize(db, command.id, 'rejected', status, providerError(e), e.message, null, e.intuitTid || null); return jsonResponse(providerError(e), status, request, env); }
      const fallbackAttempt = { stage: fallback.stage, providerAction: attempt.providerAction, providerTargetId: attempt.providerTargetId, providerRequestId: await qboInvoiceRequestId(attempt.providerAction, command.invoice_id, command.id, fallback.stage), providerPayload: fallback.payload };
      const advanced = await advanceQboInvoiceCommandAttempt(db, { commandId: command.id, expectedStage: attempt.stage, ...fallbackAttempt });
      if (!advanced?.ok) return jsonResponse({ error: 'QuickBooks fallback requires review', code: advanced?.reason }, 409, request, env);
      const persistedFallback = { stage: advanced.provider_stage, providerAction: advanced.provider_action, providerTargetId: advanced.provider_target_id, providerRequestId: advanced.provider_request_id, providerPayload: advanced.provider_payload };
      try { providerResult = await executeProvider(env, persistedFallback, command); } catch (fallbackError) { if (ambiguous(fallbackError)) return ambiguousProviderFailure(db, command, fallbackError, request, env); const status = fallbackError?.code === 'qbo-realm-mismatch' ? 409 : 500; await finalize(db, command.id, 'rejected', status, providerError(fallbackError), fallbackError.message, null, fallbackError.intuitTid || null); return jsonResponse(providerError(fallbackError), status, request, env); }
    }
    try {
    if (action !== 'delete' && !String(providerResult?.Id || '').trim()) {
      const payload = { error: 'QuickBooks accepted the request without an invoice Id; reconciliation is required.', code: 'missing-provider-invoice-id', retry_same_request: true };
      await setQboInvoiceCommandState(db, { commandId: command.id, status: 'ambiguous', responseStatus: 500, responsePayload: payload, error: payload.error });
      return jsonResponse(payload, 500, request, env);
    }
    // bill_email rides along with email_status so BOTH survive into the frozen
    // command. The raw QBO entity is gone on the provider_succeeded crash-recovery
    // path, and the email mirror below has to work there too.
    const result = action === 'delete' ? { local_target_qbo_invoice_id: null } : { qbo_invoice_id: String(providerResult.Id), id: String(providerResult.Id), doc_number: providerResult.DocNumber ?? null, email_status: providerResult.EmailStatus ?? null, bill_email: providerResult.BillEmail?.Address ?? null, total: providerResult.TotalAmt ?? null };
    await setQboInvoiceCommandState(db, { commandId: command.id, status: 'provider_succeeded', providerResult: result, intuitRequestId: providerResult?.intuitTid || null });
    command = await getQboInvoiceCommand(db, command.id); providerResult = command.provider_result;
    if (action !== 'delete' && command.target_qbo_invoice_id && String(providerResult?.qbo_invoice_id || providerResult?.id) !== String(command.target_qbo_invoice_id)) return needsReconciliation(db, command, request, env, 'QuickBooks returned a different invoice than the frozen command target.');
    } catch {
      return postProviderFailure(db, command, request, env);
    }
  }
  try {
  const fresh = (await db.select('invoices', `id=eq.${invoiceId}&limit=1`))?.[0];
  if (!fresh) return needsReconciliation(db, command, request, env, 'Invoice disappeared before QuickBooks finalization.');
  if (action === 'save' && !(await currentMatchesStoredAttempt(db, env, request, command, fresh, body))) return needsReconciliation(db, command, request, env, 'Invoice changed after QuickBooks accepted the frozen save; reload and reconcile before retrying.', fresh.qbo_invoice_id);
  if (action === 'send') {
    let currentSend;
    try { currentSend = await currentIntent(db, env, request, 'send', fresh, body, null, null, command.realm_id); } catch { return needsReconciliation(db, command, request, env, 'Invoice recipient changed after QuickBooks accepted the send; reload and reconcile before retrying.', fresh.qbo_invoice_id); }
    if (String(fresh.qbo_invoice_id || '') !== String(command.target_qbo_invoice_id || '') || currentSend.recipient !== command.intent_payload.recipient) return needsReconciliation(db, command, request, env, 'Invoice link or recipient changed after QuickBooks accepted the send; reload and reconcile before retrying.', fresh.qbo_invoice_id);
  }
  if (action === 'delete' && fresh.qbo_invoice_id != null && String(fresh.qbo_invoice_id) !== String(command.expected_qbo_invoice_id)) return needsReconciliation(db, command, request, env, 'Invoice link changed after QuickBooks accepted the delete; reload and reconcile before retrying.', fresh.qbo_invoice_id);
  if (action === 'save' && command.intent_payload?.line_update) {
    const finalizedLine = await finalizeQboInvoiceLineUpdate(db, {
      commandId: command.id, invoiceId, actor, realmId, lineUpdate,
    });
    if (!finalizedLine?.ok) {
      if (['source-mismatch', 'patch-conflict', 'command-mismatch', 'command-not-found', 'reservation-mismatch', 'invoice-locked', 'invoice-not-found', 'line-not-found'].includes(finalizedLine?.reason)) {
        return needsReconciliation(db, command, request, env, 'Invoice line changed after QuickBooks accepted the frozen save; reload and reconcile before retrying.', fresh.qbo_invoice_id);
      }
      throw new Error(`Invoice line finalization failed: ${finalizedLine?.reason || 'unknown'}`);
    }
  }
  if (action === 'save' && command.intent_payload?.line_change) {
    const finalizedLine = await finalizeQboInvoiceLineChange(db, { commandId: command.id, invoiceId, actor, realmId, lineChange });
    if (!finalizedLine?.ok) {
      if (['source-mismatch', 'change-conflict', 'command-mismatch', 'command-not-found', 'reservation-mismatch', 'invoice-locked', 'invoice-not-found', 'line-not-found'].includes(finalizedLine?.reason)) {
        return needsReconciliation(db, command, request, env, 'Invoice lines changed after QuickBooks accepted the frozen save; reload and reconcile before retrying.', fresh.qbo_invoice_id);
      }
      throw new Error(`Invoice line finalization failed: ${finalizedLine?.reason || 'unknown'}`);
    }
  }
  const target = action === 'delete' ? null : String(providerResult.qbo_invoice_id || providerResult.id || command.target_qbo_invoice_id);
  const cas = rpcObject(await db.rpc('cas_qbo_invoice_link', { p_invoice_id: invoiceId, p_expected_qbo_invoice_id: command.expected_qbo_invoice_id, p_new_qbo_invoice_id: target, p_qbo_doc_number: action === 'delete' ? null : (providerResult.doc_number ?? null), ...(action === 'send' ? { p_qbo_emailed_at: new Date().toISOString(), p_qbo_email_status: providerResult.email_status || 'EmailSent', p_sent_to_email: command.intent_payload.recipient, p_write_email_metadata: true } : {}) }));
  if (!cas?.ok) return needsReconciliation(db, command, request, env, 'QuickBooks invoice link changed concurrently; reload and review before retrying.', cas?.current_qbo_invoice_id || null);
  if (action === 'save') {
    const now = new Date().toISOString();
    const patch = { qbo_synced_at: now, qbo_sync_error: null };
    if (!command.expected_qbo_invoice_id) {
      if (!fresh.sent_at) patch.sent_at = now;
      if (!fresh.due_date) patch.due_date = qboInvoiceDateFields(fresh).DueDate || now.slice(0, 10);
    }
    await db.update('invoices', `id=eq.${invoiceId}`, patch);
  }
  const response = action === 'delete' ? { deleted: command.expected_qbo_invoice_id } : action === 'send' ? { ok: true, emailed_to: command.intent_payload.recipient, email_status: providerResult.email_status || 'EmailSent' } : { ok: true, mode: command.expected_qbo_invoice_id ? 'updated' : 'created', qbo_invoice_id: target, doc_number: providerResult.doc_number, total: providerResult.total ?? null, online_pay_warning: command.provider_stage === 'without-online-pay' ? 'Invoice synced, but online card/ACH pay could not be turned on — enable QuickBooks Payments in QuickBooks first.' : null, customer_relink: command.provider_stage === 'customer-relinked' ? 'QuickBooks customer was re-linked automatically.' : null };
  await finalize(db, command.id, 'succeeded', 200, response);
  // Mirror what QuickBooks itself reports about emailing this invoice. Every
  // create/update/send response IS a full invoice entity, so this costs no extra
  // provider call. It writes ONLY the three observation columns: qbo_emailed_at
  // remains the send path's (stamped by the CAS above), because a trigger derives
  // invoice status and CRM lead value from it. Self-guarding -- a silent no-op
  // until migration 20260807190000 is applied.
  if (action !== 'delete') {
    await mirrorQboInvoiceEmail(db, [invoiceId], {
      EmailStatus: providerResult.email_status,
      BillEmail: providerResult.bill_email ? { Address: providerResult.bill_email } : undefined,
    });
  }
  if (action === 'send') {
    await recordActivity(db, {
      invoiceId, actor, eventType: 'invoice_sent',
      recipient: command.intent_payload.recipient,
      cc: (fresh.send_cc_email || '').trim() || null,
      metadata: { email_status: providerResult.email_status || 'EmailSent', resend: Boolean(fresh.qbo_emailed_at) },
    });
  } else if (action === 'save') {
    await recordActivity(db, {
      invoiceId, actor, eventType: 'invoice_saved_to_quickbooks',
      metadata: { mode: command.expected_qbo_invoice_id ? 'updated' : 'created' },
    });
  }
  await logRun(db, 'completed', 1, null, startedAt);
    return jsonResponse(response, 200, request, env);
  } catch {
    return postProviderFailure(db, command, request, env);
  }
}
