import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';

const DIVISION_OPTIONS = [
  { value: 'water', label: 'Water Mitigation' },
  { value: 'mold', label: 'Mold Remediation' },
  { value: 'reconstruction', label: 'Reconstruction' },
  { value: 'fire', label: 'Fire' },
  { value: 'contents', label: 'Contents' },
  { value: 'general', label: 'General' },
];

const SOURCE_OPTIONS = [
  { value: 'insurance', label: 'Insurance' },
  { value: 'retail', label: 'Retail / Cash' },
  { value: 'hoa', label: 'HOA' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'tpa', label: 'TPA' },
];

const PRIORITY_OPTIONS = [
  { value: 1, label: 'Urgent' },
  { value: 2, label: 'High' },
  { value: 3, label: 'Normal' },
  { value: 4, label: 'Low' },
];

const INITIAL_PHASE = 'job_received';

export default function CreateJob() {
  const navigate = useNavigate();
  const { db, employee: currentUser } = useAuth();
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);

  // Form state — grouped by section
  const [form, setForm] = useState({
    // Job basics
    division: 'water',
    source: 'insurance',
    priority: 2,
    type_of_loss: '',

    // Client
    insured_name: '',
    client_phone: '',
    client_email: '',
    address: '',
    city: '',
    state: 'UT',
    zip: '',

    // Insurance
    insurance_company: '',
    claim_number: '',
    policy_number: '',
    adjuster_name: '',
    adjuster_phone: '',
    adjuster_email: '',
    cat_code: '',

    // Dates
    date_of_loss: '',
    target_completion: '',

    // Team
    project_manager_id: currentUser?.role === 'project_manager' ? currentUser?.id : '',
    lead_tech_id: '',

    // Notes
    internal_notes: '',
  });

  const [employees, setEmployees] = useState([]);
  const [empsLoaded, setEmpsLoaded] = useState(false);

  // Load employees on mount (lazy — only when Team section is visible)
  const loadEmployees = async () => {
    if (empsLoaded) return;
    try {
      const data = await db.select('employees', 'is_active=eq.true&order=full_name.asc&select=id,full_name,role');
      setEmployees(data);
      setEmpsLoaded(true);
    } catch (err) {
      console.error('Failed to load employees:', err);
    }
  };

  // Load on first render
  useState(() => { loadEmployees(); });

  const set = (field, value) => setForm(prev => ({ ...prev, [field]: value }));

  const handleSubmit = async () => {
    // Validate minimum required fields
    if (!form.insured_name.trim()) {
      setError('Client name is required.');
      return;
    }

    setSaving(true);
    setError(null);

    try {
      // Build the insert object — only include non-empty values
      const insert = {
        division: form.division,
        source: form.source,
        phase: INITIAL_PHASE,
        priority: form.priority,
        status: 'active',
        // job_number is auto-generated by the trigger
      };

      // Text fields — only include if non-empty
      const textFields = [
        'insured_name', 'client_phone', 'client_email', 'address', 'city', 'state', 'zip',
        'insurance_company', 'claim_number', 'policy_number', 'adjuster_name', 'adjuster_phone',
        'adjuster_email', 'cat_code', 'type_of_loss', 'internal_notes',
      ];
      for (const f of textFields) {
        if (form[f]?.trim()) insert[f] = form[f].trim();
      }

      // Dates
      if (form.date_of_loss) insert.date_of_loss = form.date_of_loss;
      if (form.target_completion) insert.target_completion = form.target_completion;

      // Team
      if (form.project_manager_id) insert.project_manager_id = form.project_manager_id;
      if (form.lead_tech_id) insert.lead_tech_id = form.lead_tech_id;

      const result = await db.insert('jobs', insert);

      if (result && result.length > 0) {
        // Navigate to the new job page
        navigate(`/jobs/${result[0].id}`, { replace: true });
      } else {
        // If insert doesn't return the row, go to jobs list
        navigate('/jobs', { replace: true });
      }
    } catch (err) {
      console.error('Create job error:', err);
      setError('Failed to create job: ' + err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="create-job-page">
      {/* Header */}
      <div className="create-job-header">
        <div>
          <button className="btn btn-ghost btn-sm" onClick={() => navigate(-1)} style={{ marginBottom: 8, gap: 4 }}>← Back</button>
          <h1 className="page-title">Create New Job</h1>
          <p className="page-subtitle">Job number will be auto-generated based on division</p>
        </div>
        <div className="create-job-header-actions">
          <button className="btn btn-secondary" onClick={() => navigate(-1)} disabled={saving}>Cancel</button>
          <button className="btn btn-primary" onClick={handleSubmit} disabled={saving}>
            {saving ? 'Creating...' : 'Create Job'}
          </button>
        </div>
      </div>

      {error && <div className="create-job-error">{error}</div>}

      <div className="create-job-grid">
        {/* ── Job Basics ── */}
        <div className="create-job-section">
          <div className="create-job-section-title">Job Information</div>

          <div className="create-job-field">
            <label className="label">Division *</label>
            <select className="input" value={form.division} onChange={e => set('division', e.target.value)}>
              {DIVISION_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </div>

          <div className="create-job-field">
            <label className="label">Source</label>
            <select className="input" value={form.source} onChange={e => set('source', e.target.value)}>
              {SOURCE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </div>

          <div className="create-job-field">
            <label className="label">Priority</label>
            <select className="input" value={form.priority} onChange={e => set('priority', parseInt(e.target.value))}>
              {PRIORITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </div>

          <div className="create-job-field">
            <label className="label">Type of Loss</label>
            <input className="input" value={form.type_of_loss} onChange={e => set('type_of_loss', e.target.value)} placeholder="e.g. Pipe burst, Storm, Sewage backup" />
          </div>

          <div className="create-job-row">
            <div className="create-job-field">
              <label className="label">Date of Loss</label>
              <input className="input" type="date" value={form.date_of_loss} onChange={e => set('date_of_loss', e.target.value)} />
            </div>
            <div className="create-job-field">
              <label className="label">Target Completion</label>
              <input className="input" type="date" value={form.target_completion} onChange={e => set('target_completion', e.target.value)} />
            </div>
          </div>
        </div>

        {/* ── Client Info ── */}
        <div className="create-job-section">
          <div className="create-job-section-title">Client Information</div>

          <div className="create-job-field">
            <label className="label">Client Name *</label>
            <input className="input" value={form.insured_name} onChange={e => set('insured_name', e.target.value)} placeholder="Full name" autoFocus />
          </div>

          <div className="create-job-row">
            <div className="create-job-field">
              <label className="label">Phone</label>
              <input className="input" type="tel" value={form.client_phone} onChange={e => set('client_phone', e.target.value)} placeholder="(801) 555-0000" />
            </div>
            <div className="create-job-field">
              <label className="label">Email</label>
              <input className="input" type="email" value={form.client_email} onChange={e => set('client_email', e.target.value)} placeholder="client@email.com" />
            </div>
          </div>

          <div className="create-job-field">
            <label className="label">Address</label>
            <input className="input" value={form.address} onChange={e => set('address', e.target.value)} placeholder="Street address" />
          </div>

          <div className="create-job-row create-job-row-3">
            <div className="create-job-field">
              <label className="label">City</label>
              <input className="input" value={form.city} onChange={e => set('city', e.target.value)} placeholder="City" />
            </div>
            <div className="create-job-field" style={{ maxWidth: 80 }}>
              <label className="label">State</label>
              <input className="input" value={form.state} onChange={e => set('state', e.target.value)} placeholder="UT" />
            </div>
            <div className="create-job-field" style={{ maxWidth: 100 }}>
              <label className="label">Zip</label>
              <input className="input" value={form.zip} onChange={e => set('zip', e.target.value)} placeholder="84601" />
            </div>
          </div>
        </div>

        {/* ── Insurance ── */}
        <div className="create-job-section">
          <div className="create-job-section-title">Insurance</div>

          <div className="create-job-field">
            <label className="label">Insurance Company</label>
            <input className="input" value={form.insurance_company} onChange={e => set('insurance_company', e.target.value)} placeholder="e.g. State Farm, Farmers, USAA" />
          </div>

          <div className="create-job-row">
            <div className="create-job-field">
              <label className="label">Claim #</label>
              <input className="input" value={form.claim_number} onChange={e => set('claim_number', e.target.value)} placeholder="Claim number" />
            </div>
            <div className="create-job-field">
              <label className="label">Policy #</label>
              <input className="input" value={form.policy_number} onChange={e => set('policy_number', e.target.value)} placeholder="Policy number" />
            </div>
          </div>

          <div className="create-job-field">
            <label className="label">Adjuster Name</label>
            <input className="input" value={form.adjuster_name} onChange={e => set('adjuster_name', e.target.value)} placeholder="Adjuster full name" />
          </div>

          <div className="create-job-row">
            <div className="create-job-field">
              <label className="label">Adjuster Phone</label>
              <input className="input" type="tel" value={form.adjuster_phone} onChange={e => set('adjuster_phone', e.target.value)} placeholder="(801) 555-0000" />
            </div>
            <div className="create-job-field">
              <label className="label">Adjuster Email</label>
              <input className="input" type="email" value={form.adjuster_email} onChange={e => set('adjuster_email', e.target.value)} placeholder="adjuster@email.com" />
            </div>
          </div>

          <div className="create-job-field">
            <label className="label">CAT Code</label>
            <input className="input" value={form.cat_code} onChange={e => set('cat_code', e.target.value)} placeholder="CAT code (if applicable)" />
          </div>
        </div>

        {/* ── Team ── */}
        <div className="create-job-section">
          <div className="create-job-section-title">Team Assignment</div>

          <div className="create-job-field">
            <label className="label">Project Manager</label>
            <select className="input" value={form.project_manager_id} onChange={e => set('project_manager_id', e.target.value)}>
              <option value="">Unassigned</option>
              {employees.map(emp => <option key={emp.id} value={emp.id}>{emp.full_name}</option>)}
            </select>
          </div>

          <div className="create-job-field">
            <label className="label">Lead Tech</label>
            <select className="input" value={form.lead_tech_id} onChange={e => set('lead_tech_id', e.target.value)}>
              <option value="">Unassigned</option>
              {employees.filter(e => e.role === 'field_tech').map(emp => <option key={emp.id} value={emp.id}>{emp.full_name}</option>)}
            </select>
          </div>

          <div className="create-job-field">
            <label className="label">Internal Notes</label>
            <textarea className="input textarea" value={form.internal_notes} onChange={e => set('internal_notes', e.target.value)} rows={4} placeholder="Initial notes about the job..." />
          </div>
        </div>
      </div>

      {/* Bottom action bar (sticky on mobile) */}
      <div className="create-job-bottom-bar">
        <button className="btn btn-secondary" onClick={() => navigate(-1)} disabled={saving}>Cancel</button>
        <button className="btn btn-primary btn-lg" onClick={handleSubmit} disabled={saving}>
          {saving ? 'Creating...' : 'Create Job'}
        </button>
      </div>
    </div>
  );
}
