/**
 * ════════════════════════════════════════════════
 * FILE: invoiceLineEdit.js  (Admin Mobile — invoice line edit contract)
 * ════════════════════════════════════════════════
 *
 * WHAT THIS DOES (plain language):
 *   Keeps the single-line editor's money-safe write shape and validation out of
 *   the screen. The database calculates `line_total`; this module deliberately
 *   never includes it or any invoice-level financial field in a write.
 *
 * USED BY: InvoiceLineEditor and AdminInvoiceLineEdit.
 * ════════════════════════════════════════════════
 */

const round2 = (value) => Math.round(Number(value || 0) * 100) / 100;
const nullIfBlank = (value) => {
  const text = String(value || '').trim();
  return text || null;
};

/** Exact editable source columns on invoice_line_items; generated totals stay DB-owned. */
export const INVOICE_LINE_SAFE_COLUMNS = Object.freeze([
  'description',
  'qbo_item_id',
  'qbo_item_name',
  'qbo_class_id',
  'qbo_class_name',
  'quantity',
  'unit_price',
]);

export function buildInvoiceLineUpdate(line) {
  return {
    description: line.description || '',
    qbo_item_id: nullIfBlank(line.qbo_item_id),
    qbo_item_name: nullIfBlank(line.qbo_item_name),
    qbo_class_id: nullIfBlank(line.qbo_class_id),
    qbo_class_name: nullIfBlank(line.qbo_class_name),
    quantity: Number(line.quantity),
    unit_price: Number(line.unit_price),
  };
}

export function invoiceLineValidationError(line) {
  if (!Number.isFinite(Number(line.quantity))) return 'Enter a valid quantity.';
  if (!Number.isFinite(Number(line.unit_price))) return 'Enter a valid rate.';
  return '';
}

/** Live display only; the persisted line_total remains generated by the database. */
export const invoiceLineAmount = (line) => round2(Number(line.quantity || 0) * Number(line.unit_price || 0));
