/**
 * ════════════════════════════════════════════════
 * FILE: invoiceLineEdit.js  (Admin Mobile — invoice line edit contract)
 * ════════════════════════════════════════════════
 *
 * WHAT THIS DOES (plain language):
 *   Keeps the single-line editor's money-safe write shape and validation out of
 *   the screen. The database calculates `line_total`; this module deliberately
 *   never includes it or any invoice-level financial field in a write.
 *
 * DEPENDS ON:
 *   Packages:  none
 *   Internal:  none
 *   Data:      reads  → none (pure transformation helpers)
 *              writes → none (consumers submit the returned source-field patch)
 *
 * NOTES / GOTCHAS:
 *   - Used by InvoiceLineEditor and AdminInvoiceLineEdit.
 *   - Only source fields from invoice_line_items are returned. `line_total` and
 *     invoice-level money/status fields remain database-owned.
 * ════════════════════════════════════════════════
 */

const round2 = (value) => Math.round(Number(value || 0) * 100) / 100;
const nullIfBlank = (value) => {
  const text = String(value || '').trim();
  return text || null;
};

/** Exact editable source columns on invoice_line_items; generated totals stay DB-owned. */
export const INVOICE_LINE_SAFE_COLUMNS = Object.freeze([
  'description',
  'qbo_item_id',
  'qbo_item_name',
  'qbo_class_id',
  'qbo_class_name',
  'quantity',
  'unit_price',
]);

export function buildInvoiceLineUpdate(line) {
  return {
    description: line.description || '',
    qbo_item_id: nullIfBlank(line.qbo_item_id),
    qbo_item_name: nullIfBlank(line.qbo_item_name),
    qbo_class_id: nullIfBlank(line.qbo_class_id),
    qbo_class_name: nullIfBlank(line.qbo_class_name),
    quantity: Number(line.quantity),
    unit_price: Number(line.unit_price),
  };
}

/** Stable source patch used by all add/update QBO document commands. */
export const buildInvoiceLinePatch = buildInvoiceLineUpdate;

export function buildInvoiceLineChange(kind, line, orderedLineIds) {
  if (kind === 'delete') return { kind, line_id: line.id };
  if (kind === 'reorder') return { kind, ordered_line_ids: orderedLineIds };
  return kind === 'create'
    ? { kind, patch: buildInvoiceLinePatch(line) }
    : { kind: 'update', line_id: line.id, patch: buildInvoiceLinePatch(line) };
}

export function invoiceLineValidationError(line) {
  if (!String(line.description || '').trim()) return 'Enter a description.';
  if (!Number.isFinite(Number(line.quantity))) return 'Enter a valid quantity.';
  if (!Number.isFinite(Number(line.unit_price))) return 'Enter a valid rate.';
  return '';
}

export function invoiceLineChangeValidationError(line, creating = false) {
  const error = invoiceLineValidationError(line);
  if (error) return error;
  if (creating && Number(line.quantity) * Number(line.unit_price) <= 0) return 'Enter a positive amount for a new line item.';
  return '';
}

/** Live display only; the persisted line_total remains generated by the database. */
export const invoiceLineAmount = (line) => round2(Number(line.quantity || 0) * Number(line.unit_price || 0));
