// ════════════════════════════════════════════════
// FILE: codeContext.js
// ════════════════════════════════════════════════
//
// WHAT THIS DOES (plain language):
//   The brains behind the upr_code_context MCP tool. Given a plain-English
//   feature name like "invoice payment reconciliation", it looks up a checked-in
//   keyword map (codeIndex.js) and returns a compact list of where that feature
//   lives in the UPR codebase — the relevant pages, components, background
//   workers, database functions, tables, tests, coding-standard docs, and any
//   "gold-standard" implementation the rules docs point to. It expands UPR's
//   business vocabulary (claim/job/estimate/invoice/QBO/Encircle/Twilio…) with
//   synonyms so a loose phrase still finds the right files. Pure functions only —
//   no network, no database, no filesystem — so it runs anywhere and is testable.
//
// WHERE IT LIVES:
//   Imported by:  src/tools.js  (the upr_code_context tool's run())
//   Reads:        src/codeIndex.js  (generated by `npm run build-index`)
//
// DEPENDS ON:
//   Internal:  ./codeIndex.js (the generated INDEX)
//
// NOTES / GOTCHAS:
//   - Read-only by construction: it only reads the imported constant. No writes.
//   - The output is deliberately capped (paths only, small per-category limits)
//     to stay well under ~2k tokens per call.
//   - Synonym clusters are the one place to teach the tool new UPR vocabulary;
//     add a term to a cluster and both directions expand automatically.
// ════════════════════════════════════════════════

import { INDEX } from './codeIndex.js';

// ─── SECTION: Vocabulary ──────────────
// Synonym clusters for UPR's business domain. Any query token in a cluster pulls
// in the whole cluster, so "invoicing" finds files tagged "qbo"/"billing"/"payment".
export const SYNONYM_CLUSTERS = [
  ['invoice', 'invoicing', 'billing', 'bill', 'qbo', 'quickbooks', 'intuit', 'ar', 'receivable'],
  ['estimate', 'estimates', 'xactimate', 'oop', 'quote', 'pricing', 'scope'],
  ['claim', 'claims', 'insurance', 'adjuster', 'carrier', 'encircle', 'xactimate'],
  ['job', 'jobs', 'production', 'phase', 'phases'],
  ['collections', 'collection', 'overdue', 'dunning', 'receivable', 'ar', 'aging'],
  ['payment', 'pay', 'stripe', 'charge', 'reconcile', 'reconciliation', 'qbo'],
  ['reconcile', 'reconciliation', 'match', 'sync', 'payment'],
  ['tech', 'technician', 'field', 'mobile', 'crew', 'clock', 'appointment'],
  ['crm', 'lead', 'leads', 'contact', 'contacts', 'pipeline', 'marketing', 'sequence', 'segment', 'automation'],
  ['scope', 'demo', 'sheet', 'damage', 'moisture', 'room', 'rooms'],
  ['qbo', 'quickbooks', 'intuit', 'invoice', 'estimate', 'payment', 'sync'],
  ['encircle', 'claim', 'room', 'rooms', 'sync', 'xactimate', 'import'],
  ['twilio', 'sms', 'message', 'messages', 'text', 'conversation', 'conversations', 'consent'],
  ['sms', 'twilio', 'message', 'text', 'conversation', 'consent', 'compliance'],
  ['email', 'resend', 'message', 'conversation', 'esign', 'inbox', 'deliverability'],
  ['esign', 'sign', 'signature', 'signpage', 'consent'],
  ['schedule', 'scheduling', 'appointment', 'appointments', 'calendar', 'dispatch', 'crew'],
  ['water', 'moisture', 'reading', 'readings', 'drying', 'equipment', 'hydro'],
  ['time', 'clock', 'payroll', 'hours', 'tracking', 'timesheet'],
  ['customer', 'customers', 'contact', 'contacts', 'client', 'homeowner'],
  ['report', 'reports', 'analytics', 'dashboard', 'forecast', 'metrics', 'overview'],
  ['auth', 'login', 'permission', 'permissions', 'access', 'role', 'roles'],
  ['document', 'documents', 'file', 'files', 'photo', 'photos', 'media', 'upload'],
  ['task', 'tasks', 'checklist', 'todo'],
  ['calendar', 'google', 'gcal', 'schedule'],
  ['notification', 'notifications', 'push', 'alert'],
];

// STOP words are also stripped from the query so "the invoice for a job" tokenizes clean.
const STOP = new Set([
  'the', 'and', 'for', 'a', 'an', 'to', 'of', 'in', 'on', 'with', 'how', 'where',
  'what', 'is', 'are', 'does', 'do', 'this', 'that', 'find', 'show', 'me', 'all',
  'system', 'feature', 'flow', 'page', 'code', 'get', 'set',
]);

// Build a fast lookup: token → set of cluster members (deduped, self-excluded not needed).
const SYNONYM_MAP = (() => {
  const map = new Map();
  for (const cluster of SYNONYM_CLUSTERS) {
    for (const word of cluster) {
      const bucket = map.get(word) || new Set();
      for (const w of cluster) bucket.add(w);
      map.set(word, bucket);
    }
  }
  return map;
})();

// ─── SECTION: Helpers ──────────────

// Split a phrase / identifier into lowercase keyword tokens (mirrors build-index).
export function tokenize(str) {
  if (!str) return [];
  return String(str)
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .toLowerCase()
    .split(/\s+/)
    .filter((t) => t && t.length > 1 && !STOP.has(t));
}

// Expand a set of query tokens with their synonym-cluster members.
// Returns { primary:Set (the user's own tokens), expanded:Set (primary + synonyms) }.
export function expandTokens(tokens) {
  const primary = new Set(tokens);
  const expanded = new Set(tokens);
  for (const t of tokens) {
    const syns = SYNONYM_MAP.get(t);
    if (syns) for (const s of syns) expanded.add(s);
  }
  return { primary, expanded };
}

// Score an entry's tokens against the query. A direct (user-typed) token hit is
// worth more than a synonym-only hit, so the most literal matches rank first.
export function scoreEntry(entryTokens, primary, expanded) {
  if (!entryTokens || !entryTokens.length) return 0;
  let score = 0;
  for (const t of entryTokens) {
    if (primary.has(t)) score += 3;
    else if (expanded.has(t)) score += 1;
  }
  return score;
}

// Rank a list of entries and return the top `limit` above zero score.
// `getPath` extracts the display value; ties break by fewer tokens (more specific).
function rank(entries, primary, expanded, limit, getPath) {
  const scored = [];
  for (const e of entries) {
    const score = scoreEntry(e.tokens, primary, expanded);
    if (score > 0) scored.push({ e, score });
  }
  scored.sort((a, b) => b.score - a.score || (a.e.tokens.length - b.e.tokens.length));
  return scored.slice(0, limit).map(({ e }) => getPath(e));
}

// ─── SECTION: Search ──────────────

// Per-category result caps — keep the whole payload small (well under ~2k tokens).
const CAPS = {
  pages: 8, components: 8, workers: 10, rpcs: 12, tables: 10, tests: 6, rules: 6, gold: 5, docs: 6,
};

/**
 * searchCodeContext(feature, opts, index)
 *   feature     — plain-English feature phrase (required, non-empty)
 *   opts.maxResults — optional overall tightening knob (default: the CAPS above);
 *                     when given, each category is capped at min(cap, maxResults).
 *   index       — the keyword map (defaults to the checked-in INDEX; injectable for tests)
 * Returns a compact { feature, matched_terms, pages, components, workers, rpcs,
 *   tables, tests, rules, gold_standards, docs } — paths/names only.
 */
export function searchCodeContext(feature, opts = {}, index = INDEX) {
  const raw = String(feature || '').trim();
  if (!raw) throw new Error('feature is required (e.g. "invoice payment reconciliation")');

  const queryTokens = tokenize(raw);
  const { primary, expanded } = expandTokens(queryTokens);

  const cap = (name) => {
    const base = CAPS[name] || 6;
    const m = opts.maxResults;
    return m && m > 0 ? Math.min(base, m) : base;
  };

  const pages = rank(index.pages || [], primary, expanded, cap('pages'), (e) => e.path);
  const components = rank(index.components || [], primary, expanded, cap('components'), (e) => e.path);
  const workers = rank(index.workers || [], primary, expanded, cap('workers'), (e) => e.path);
  const rpcs = rank(index.rpcs || [], primary, expanded, cap('rpcs'), (e) => e.name);
  const tables = rank(index.tables || [], primary, expanded, cap('tables'), (e) => e.name);
  const tests = rank(index.tests || [], primary, expanded, cap('tests'), (e) => e.path);
  const docs = rank(index.topics || [], primary, expanded, cap('docs'), (e) => e.title);

  const rules = rankObjects(index.rules || [], primary, expanded, cap('rules'),
    (e) => ({ path: e.path, governs: e.summary || e.title }));

  const gold = rankObjects(index.gold || [], primary, expanded, cap('gold'),
    (e) => ({ path: e.path, why: e.reason, source: e.source }));

  const matched = [...expanded].filter((t) => !primary.has(t));

  return {
    feature: raw,
    query_terms: [...primary],
    synonyms_applied: matched,
    pages,
    components,
    workers,
    rpcs,
    tables,
    tests,
    rules,
    gold_standards: gold,
    related_docs: docs,
  };
}

// Like rank(), but returns richer objects (for rules/gold where a reason helps).
function rankObjects(entries, primary, expanded, limit, project) {
  const scored = [];
  for (const e of entries) {
    const score = scoreEntry(e.tokens, primary, expanded);
    if (score > 0) scored.push({ e, score });
  }
  scored.sort((a, b) => b.score - a.score || (a.e.tokens.length - b.e.tokens.length));
  return scored.slice(0, limit).map(({ e }) => project(e));
}
