-- ROLLBACK for 2026-06-24 hardening. Restores the prior permissive baseline.
-- Pure DB, no deploy. Apply this whole file to fully revert.

BEGIN;

-- Table policies: drop authenticated copies, recreate originals
DROP POLICY IF EXISTS all_delete_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS all_insert_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS all_select_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS all_update_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS appointment_dependencies_delete ON public.appointment_dependencies;
DROP POLICY IF EXISTS appointment_dependencies_insert ON public.appointment_dependencies;
DROP POLICY IF EXISTS appointment_dependencies_select ON public.appointment_dependencies;
DROP POLICY IF EXISTS appointment_dependencies_update ON public.appointment_dependencies;
DROP POLICY IF EXISTS all_delete_appointments ON public.appointments;
DROP POLICY IF EXISTS all_insert_appointments ON public.appointments;
DROP POLICY IF EXISTS all_select_appointments ON public.appointments;
DROP POLICY IF EXISTS all_update_appointments ON public.appointments;
DROP POLICY IF EXISTS anon_delete_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS anon_insert_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS anon_select_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS anon_update_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS allow_anon_read_campaigns ON public.campaigns;
DROP POLICY IF EXISTS anon_insert_claims ON public.claims;
DROP POLICY IF EXISTS anon_read_claims ON public.claims;
DROP POLICY IF EXISTS anon_update_claims ON public.claims;
DROP POLICY IF EXISTS claims_anon_delete ON public.claims;
DROP POLICY IF EXISTS ca_delete ON public.contact_addresses;
DROP POLICY IF EXISTS ca_insert ON public.contact_addresses;
DROP POLICY IF EXISTS ca_select ON public.contact_addresses;
DROP POLICY IF EXISTS ca_update ON public.contact_addresses;
DROP POLICY IF EXISTS contact_jobs_anon_delete ON public.contact_jobs;
DROP POLICY IF EXISTS contact_jobs_anon_insert ON public.contact_jobs;
DROP POLICY IF EXISTS contact_jobs_anon_select ON public.contact_jobs;
DROP POLICY IF EXISTS contact_jobs_anon_update ON public.contact_jobs;
DROP POLICY IF EXISTS allow_anon_insert_contacts ON public.contacts;
DROP POLICY IF EXISTS allow_anon_read_contacts ON public.contacts;
DROP POLICY IF EXISTS allow_anon_update_contacts ON public.contacts;
DROP POLICY IF EXISTS allow_anon_insert_conversation_participants ON public.conversation_participants;
DROP POLICY IF EXISTS allow_anon_read_conversation_participants ON public.conversation_participants;
DROP POLICY IF EXISTS allow_anon_insert_conversations ON public.conversations;
DROP POLICY IF EXISTS allow_anon_read_conversations ON public.conversations;
DROP POLICY IF EXISTS allow_anon_update_conversations ON public.conversations;
DROP POLICY IF EXISTS demo_sheet_schemas_all ON public.demo_sheet_schemas;
DROP POLICY IF EXISTS "Own tokens or admin read" ON public.device_tokens;
DROP POLICY IF EXISTS dispatch_board_jobs_delete ON public.dispatch_board_jobs;
DROP POLICY IF EXISTS dispatch_board_jobs_insert ON public.dispatch_board_jobs;
DROP POLICY IF EXISTS dispatch_board_jobs_select ON public.dispatch_board_jobs;
DROP POLICY IF EXISTS "anon read document_templates" ON public.document_templates;
DROP POLICY IF EXISTS "anon write document_templates" ON public.document_templates;
DROP POLICY IF EXISTS anon_read_employee_page_access ON public.employee_page_access;
DROP POLICY IF EXISTS allow_anon_read_employees ON public.employees;
DROP POLICY IF EXISTS equip_authenticated_all ON public.equipment_placements;
DROP POLICY IF EXISTS anon_read_flags ON public.feature_flags;
DROP POLICY IF EXISTS anon_read_carriers ON public.insurance_carriers;
DROP POLICY IF EXISTS anon_write_insurance_carriers ON public.insurance_carriers;
DROP POLICY IF EXISTS allow_anon_read_invoices ON public.invoices;
DROP POLICY IF EXISTS anon_delete_job_documents ON public.job_documents;
DROP POLICY IF EXISTS anon_insert_job_documents ON public.job_documents;
DROP POLICY IF EXISTS anon_select_job_documents ON public.job_documents;
DROP POLICY IF EXISTS anon_update_job_documents ON public.job_documents;
DROP POLICY IF EXISTS job_documents_delete ON public.job_documents;
DROP POLICY IF EXISTS job_documents_insert ON public.job_documents;
DROP POLICY IF EXISTS job_documents_select ON public.job_documents;
DROP POLICY IF EXISTS job_documents_update ON public.job_documents;
DROP POLICY IF EXISTS anon_delete_job_notes ON public.job_notes;
DROP POLICY IF EXISTS anon_insert_job_notes ON public.job_notes;
DROP POLICY IF EXISTS anon_select_job_notes ON public.job_notes;
DROP POLICY IF EXISTS anon_update_job_notes ON public.job_notes;
DROP POLICY IF EXISTS job_number_sequences_insert ON public.job_number_sequences;
DROP POLICY IF EXISTS job_number_sequences_select ON public.job_number_sequences;
DROP POLICY IF EXISTS job_number_sequences_update ON public.job_number_sequences;
DROP POLICY IF EXISTS allow_anon_insert_phase_history ON public.job_phase_history;
DROP POLICY IF EXISTS allow_anon_read_phase_history ON public.job_phase_history;
DROP POLICY IF EXISTS allow_anon_read_phases ON public.job_phases;
DROP POLICY IF EXISTS anon_delete_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS anon_insert_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS anon_read_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS anon_update_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS job_schedules_delete ON public.job_schedules;
DROP POLICY IF EXISTS job_schedules_insert ON public.job_schedules;
DROP POLICY IF EXISTS job_schedules_select ON public.job_schedules;
DROP POLICY IF EXISTS job_schedules_update ON public.job_schedules;
DROP POLICY IF EXISTS anon_all ON public.job_supplements;
DROP POLICY IF EXISTS job_tasks_delete ON public.job_tasks;
DROP POLICY IF EXISTS job_tasks_insert ON public.job_tasks;
DROP POLICY IF EXISTS job_tasks_select ON public.job_tasks;
DROP POLICY IF EXISTS job_tasks_update ON public.job_tasks;
DROP POLICY IF EXISTS allow_anon_read_job_time_entries ON public.job_time_entries;
DROP POLICY IF EXISTS allow_anon_insert_jobs ON public.jobs;
DROP POLICY IF EXISTS allow_anon_read_jobs ON public.jobs;
DROP POLICY IF EXISTS allow_anon_update_jobs ON public.jobs;
DROP POLICY IF EXISTS allow_anon_read_templates ON public.message_templates;
DROP POLICY IF EXISTS allow_anon_read_messages ON public.messages;
DROP POLICY IF EXISTS allow_anon_write_messages ON public.messages;
DROP POLICY IF EXISTS moisture_authenticated_all ON public.moisture_readings;
DROP POLICY IF EXISTS nav_permissions_anon_all ON public.nav_permissions;
DROP POLICY IF EXISTS anon_insert_notification_queue ON public.notification_queue;
DROP POLICY IF EXISTS anon_select_notification_queue ON public.notification_queue;
DROP POLICY IF EXISTS anon_update_notification_queue ON public.notification_queue;
DROP POLICY IF EXISTS notifications_select ON public.notifications;
DROP POLICY IF EXISTS allow_anon_delete_payments ON public.payments;
DROP POLICY IF EXISTS allow_anon_insert_payments ON public.payments;
DROP POLICY IF EXISTS allow_anon_select_payments ON public.payments;
DROP POLICY IF EXISTS allow_anon_update_payments ON public.payments;
DROP POLICY IF EXISTS anon_read_referral_sources ON public.referral_sources;
DROP POLICY IF EXISTS anon_write_referral_sources ON public.referral_sources;
DROP POLICY IF EXISTS rooms_authenticated_all ON public.rooms;
DROP POLICY IF EXISTS allow_anon_read_schedule_blocks ON public.schedule_blocks;
DROP POLICY IF EXISTS schedule_templates_delete ON public.schedule_templates;
DROP POLICY IF EXISTS schedule_templates_insert ON public.schedule_templates;
DROP POLICY IF EXISTS schedule_templates_select ON public.schedule_templates;
DROP POLICY IF EXISTS schedule_templates_update ON public.schedule_templates;
DROP POLICY IF EXISTS allow_anon_insert_scheduled_messages ON public.scheduled_messages;
DROP POLICY IF EXISTS allow_anon_read_scheduled_messages ON public.scheduled_messages;
DROP POLICY IF EXISTS anon_insert_sign_requests ON public.sign_requests;
DROP POLICY IF EXISTS anon_select_sign_requests ON public.sign_requests;
DROP POLICY IF EXISTS anon_update_sign_requests ON public.sign_requests;
DROP POLICY IF EXISTS allow_anon_insert_consent_log ON public.sms_consent_log;
DROP POLICY IF EXISTS allow_anon_read_consent_log ON public.sms_consent_log;
DROP POLICY IF EXISTS anon_insert_system_events ON public.system_events;
DROP POLICY IF EXISTS anon_select_system_events ON public.system_events;
DROP POLICY IF EXISTS tech_feedback_all ON public.tech_feedback;
DROP POLICY IF EXISTS template_dependencies_delete ON public.template_dependencies;
DROP POLICY IF EXISTS template_dependencies_insert ON public.template_dependencies;
DROP POLICY IF EXISTS template_dependencies_select ON public.template_dependencies;
DROP POLICY IF EXISTS template_dependencies_update ON public.template_dependencies;
DROP POLICY IF EXISTS template_phases_delete ON public.template_phases;
DROP POLICY IF EXISTS template_phases_insert ON public.template_phases;
DROP POLICY IF EXISTS template_phases_select ON public.template_phases;
DROP POLICY IF EXISTS template_phases_update ON public.template_phases;
DROP POLICY IF EXISTS template_tasks_delete ON public.template_tasks;
DROP POLICY IF EXISTS template_tasks_insert ON public.template_tasks;
DROP POLICY IF EXISTS template_tasks_select ON public.template_tasks;
DROP POLICY IF EXISTS template_tasks_update ON public.template_tasks;
DROP POLICY IF EXISTS anon_insert_worker_runs ON public.worker_runs;
DROP POLICY IF EXISTS anon_read_worker_runs ON public.worker_runs;
DROP POLICY IF EXISTS anon_update_worker_runs ON public.worker_runs;
CREATE POLICY all_delete_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY all_insert_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY all_select_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY all_update_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY appointment_dependencies_delete ON public.appointment_dependencies AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY appointment_dependencies_insert ON public.appointment_dependencies AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY appointment_dependencies_select ON public.appointment_dependencies AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY appointment_dependencies_update ON public.appointment_dependencies AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY all_delete_appointments ON public.appointments AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY all_insert_appointments ON public.appointments AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY all_select_appointments ON public.appointments AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY all_update_appointments ON public.appointments AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_delete_automation_rules ON public.automation_rules AS PERMISSIVE FOR DELETE TO anon USING (true);
CREATE POLICY anon_insert_automation_rules ON public.automation_rules AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_select_automation_rules ON public.automation_rules AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_update_automation_rules ON public.automation_rules AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_campaigns ON public.campaigns AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_insert_claims ON public.claims AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_read_claims ON public.claims AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_update_claims ON public.claims AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY claims_anon_delete ON public.claims AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY ca_delete ON public.contact_addresses AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY ca_insert ON public.contact_addresses AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY ca_select ON public.contact_addresses AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY ca_update ON public.contact_addresses AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY contact_jobs_anon_delete ON public.contact_jobs AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY contact_jobs_anon_insert ON public.contact_jobs AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY contact_jobs_anon_select ON public.contact_jobs AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY contact_jobs_anon_update ON public.contact_jobs AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY allow_anon_insert_contacts ON public.contacts AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_contacts ON public.contacts AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_update_contacts ON public.contacts AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_insert_conversation_participants ON public.conversation_participants AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_conversation_participants ON public.conversation_participants AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_insert_conversations ON public.conversations AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_conversations ON public.conversations AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_update_conversations ON public.conversations AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY demo_sheet_schemas_all ON public.demo_sheet_schemas AS PERMISSIVE FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Own tokens or admin read" ON public.device_tokens AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY dispatch_board_jobs_delete ON public.dispatch_board_jobs AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY dispatch_board_jobs_insert ON public.dispatch_board_jobs AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY dispatch_board_jobs_select ON public.dispatch_board_jobs AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon read document_templates" ON public.document_templates AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "anon write document_templates" ON public.document_templates AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_read_employee_page_access ON public.employee_page_access AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY allow_anon_read_employees ON public.employees AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY equip_authenticated_all ON public.equipment_placements AS PERMISSIVE FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_read_flags ON public.feature_flags AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_read_carriers ON public.insurance_carriers AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_write_insurance_carriers ON public.insurance_carriers AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_invoices ON public.invoices AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_delete_job_documents ON public.job_documents AS PERMISSIVE FOR DELETE TO anon USING (true);
CREATE POLICY anon_insert_job_documents ON public.job_documents AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_select_job_documents ON public.job_documents AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_update_job_documents ON public.job_documents AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY job_documents_delete ON public.job_documents AS PERMISSIVE FOR DELETE TO public USING (true);
CREATE POLICY job_documents_insert ON public.job_documents AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY job_documents_select ON public.job_documents AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY job_documents_update ON public.job_documents AS PERMISSIVE FOR UPDATE TO public USING (true);
CREATE POLICY anon_delete_job_notes ON public.job_notes AS PERMISSIVE FOR DELETE TO anon USING (true);
CREATE POLICY anon_insert_job_notes ON public.job_notes AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_select_job_notes ON public.job_notes AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_update_job_notes ON public.job_notes AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY job_number_sequences_insert ON public.job_number_sequences AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY job_number_sequences_select ON public.job_number_sequences AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY job_number_sequences_update ON public.job_number_sequences AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY allow_anon_insert_phase_history ON public.job_phase_history AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_phase_history ON public.job_phase_history AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_read_phases ON public.job_phases AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_delete_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY anon_insert_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY anon_read_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_update_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY job_schedules_delete ON public.job_schedules AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY job_schedules_insert ON public.job_schedules AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY job_schedules_select ON public.job_schedules AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY job_schedules_update ON public.job_schedules AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.job_supplements AS PERMISSIVE FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY job_tasks_delete ON public.job_tasks AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY job_tasks_insert ON public.job_tasks AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY job_tasks_select ON public.job_tasks AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY job_tasks_update ON public.job_tasks AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_job_time_entries ON public.job_time_entries AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_insert_jobs ON public.jobs AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_jobs ON public.jobs AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_update_jobs ON public.jobs AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_templates ON public.message_templates AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_read_messages ON public.messages AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_write_messages ON public.messages AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY moisture_authenticated_all ON public.moisture_readings AS PERMISSIVE FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY nav_permissions_anon_all ON public.nav_permissions AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_insert_notification_queue ON public.notification_queue AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_select_notification_queue ON public.notification_queue AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_update_notification_queue ON public.notification_queue AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY notifications_select ON public.notifications AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY allow_anon_delete_payments ON public.payments AS PERMISSIVE FOR DELETE TO anon USING (true);
CREATE POLICY allow_anon_insert_payments ON public.payments AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_select_payments ON public.payments AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY allow_anon_update_payments ON public.payments AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_read_referral_sources ON public.referral_sources AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_write_referral_sources ON public.referral_sources AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY rooms_authenticated_all ON public.rooms AS PERMISSIVE FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_schedule_blocks ON public.schedule_blocks AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY schedule_templates_delete ON public.schedule_templates AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY schedule_templates_insert ON public.schedule_templates AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY schedule_templates_select ON public.schedule_templates AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY schedule_templates_update ON public.schedule_templates AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_insert_scheduled_messages ON public.scheduled_messages AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_scheduled_messages ON public.scheduled_messages AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_insert_sign_requests ON public.sign_requests AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_select_sign_requests ON public.sign_requests AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_update_sign_requests ON public.sign_requests AS PERMISSIVE FOR UPDATE TO anon USING (true);
CREATE POLICY allow_anon_insert_consent_log ON public.sms_consent_log AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY allow_anon_read_consent_log ON public.sms_consent_log AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY anon_insert_system_events ON public.system_events AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_select_system_events ON public.system_events AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY tech_feedback_all ON public.tech_feedback AS PERMISSIVE FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY template_dependencies_delete ON public.template_dependencies AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY template_dependencies_insert ON public.template_dependencies AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY template_dependencies_select ON public.template_dependencies AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY template_dependencies_update ON public.template_dependencies AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY template_phases_delete ON public.template_phases AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY template_phases_insert ON public.template_phases AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY template_phases_select ON public.template_phases AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY template_phases_update ON public.template_phases AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY template_tasks_delete ON public.template_tasks AS PERMISSIVE FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY template_tasks_insert ON public.template_tasks AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY template_tasks_select ON public.template_tasks AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY template_tasks_update ON public.template_tasks AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_insert_worker_runs ON public.worker_runs AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY anon_read_worker_runs ON public.worker_runs AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_update_worker_runs ON public.worker_runs AS PERMISSIVE FOR UPDATE TO anon, authenticated USING (true);

-- View / table grants
GRANT ALL ON public.active_jobs, public.billing_overview, public.demo_sheets, public.job_equipment_costs, public.todays_schedule TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;

-- Function search_path reset
ALTER FUNCTION public.add_adhoc_job_task(p_job_id uuid, p_title text, p_phase_name text, p_phase_color text, p_appointment_id uuid, p_target_date date, p_job_schedule_phase_id uuid) RESET search_path;
ALTER FUNCTION public.add_custom_schedule_phase(p_job_id uuid, p_phase_name text, p_phase_color text, p_target_start date, p_target_end date, p_duration_days integer, p_sort_order integer) RESET search_path;
ALTER FUNCTION public.add_related_job(p_source_job_id uuid, p_division text, p_priority integer, p_type_of_loss text, p_internal_notes text, p_project_manager_id uuid, p_lead_tech_id uuid, p_invoiced_value numeric) RESET search_path;
ALTER FUNCTION public.apply_schedule_plan(p_job_id uuid, p_template_id uuid, p_start_date date, p_skip_weekends boolean, p_phase_overrides jsonb, p_duration_overrides jsonb, p_created_by uuid) RESET search_path;
ALTER FUNCTION public.approve_time_entries(p_entry_ids uuid[], p_approved_by uuid, p_approved boolean) RESET search_path;
ALTER FUNCTION public.assign_tasks_to_appointment(p_appointment_id uuid, p_task_ids uuid[]) RESET search_path;
ALTER FUNCTION public.bust_postgrest_cache() RESET search_path;
ALTER FUNCTION public.clock_appointment_action(p_appointment_id uuid, p_employee_id uuid, p_action text, p_lat numeric, p_lng numeric, p_accuracy numeric) RESET search_path;
ALTER FUNCTION public.complete_sign_request(p_token uuid, p_signer_name text, p_signer_ip text, p_signed_file_path text, p_consent_terms boolean, p_consent_commitment boolean, p_consent_esign boolean, p_consent_authority boolean) RESET search_path;
ALTER FUNCTION public.create_job_with_contact(p_contact_id uuid, p_contact_name text, p_contact_phone text, p_contact_email text, p_contact_role text, p_billing_address text, p_billing_city text, p_billing_state text, p_billing_zip text, p_insurance_carrier text, p_policy_number text, p_division text, p_source text, p_priority integer, p_type_of_loss text, p_date_of_loss date, p_target_completion date, p_address text, p_city text, p_state text, p_zip text, p_insurance_company text, p_claim_number text, p_job_policy_number text, p_adjuster_name text, p_adjuster_phone text, p_adjuster_email text, p_cat_code text, p_project_manager_id uuid, p_lead_tech_id uuid, p_internal_notes text) RESET search_path;
ALTER FUNCTION public.create_room(p_job_id uuid, p_name text, p_area_sqft numeric, p_ceiling_height_ft numeric, p_sort_order integer, p_client_id uuid, p_created_by uuid) RESET search_path;
ALTER FUNCTION public.create_room_for_claim(p_claim_id uuid, p_name text, p_area_sqft numeric, p_ceiling_height_ft numeric, p_sort_order integer, p_client_id uuid, p_created_by uuid) RESET search_path;
ALTER FUNCTION public.create_sign_request(p_job_id uuid, p_contact_id uuid, p_doc_type text, p_signer_name text, p_signer_email text, p_sent_by uuid, p_divisions text[]) RESET search_path;
ALTER FUNCTION public.delete_appointment(p_appointment_id uuid) RESET search_path;
ALTER FUNCTION public.delete_contact_address(p_address_id uuid, p_contact_id uuid) RESET search_path;
ALTER FUNCTION public.delete_employee_page_access(p_employee_id uuid, p_nav_key text) RESET search_path;
ALTER FUNCTION public.delete_feature_flag(p_key text) RESET search_path;
ALTER FUNCTION public.delete_insurance_carrier(p_id uuid) RESET search_path;
ALTER FUNCTION public.delete_reading(p_reading_id uuid) RESET search_path;
ALTER FUNCTION public.delete_referral_source(p_id uuid) RESET search_path;
ALTER FUNCTION public.delete_room(p_room_id uuid) RESET search_path;
ALTER FUNCTION public.finish_appointment(p_appointment_id uuid, p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_all_employees() RESET search_path;
ALTER FUNCTION public.get_all_permissions() RESET search_path;
ALTER FUNCTION public.get_appointment_detail(p_appointment_id uuid) RESET search_path;
ALTER FUNCTION public.get_appointment_tasks(p_appointment_id uuid) RESET search_path;
ALTER FUNCTION public.get_appointments_range(p_start_date date, p_end_date date) RESET search_path;
ALTER FUNCTION public.get_ar_jobs() RESET search_path;
ALTER FUNCTION public.get_assigned_tasks(p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_claim_activity(p_claim_id uuid) RESET search_path;
ALTER FUNCTION public.get_claim_appointments(p_claim_id uuid) RESET search_path;
ALTER FUNCTION public.get_claim_detail(p_claim_id uuid) RESET search_path;
ALTER FUNCTION public.get_claim_jobs(p_claim_id uuid) RESET search_path;
ALTER FUNCTION public.get_claim_rooms(p_claim_id uuid) RESET search_path;
ALTER FUNCTION public.get_claims_list() RESET search_path;
ALTER FUNCTION public.get_contact_addresses(p_contact_id uuid) RESET search_path;
ALTER FUNCTION public.get_customer_detail(p_contact_id uuid) RESET search_path;
ALTER FUNCTION public.get_customers_list(p_search text, p_limit integer, p_offset integer) RESET search_path;
ALTER FUNCTION public.get_dashboard_stats() RESET search_path;
ALTER FUNCTION public.get_dispatch_board(p_start_date date, p_end_date date, p_auto_show boolean) RESET search_path;
ALTER FUNCTION public.get_dispatch_events(p_start_date date, p_end_date date) RESET search_path;
ALTER FUNCTION public.get_dispatch_panel_jobs() RESET search_path;
ALTER FUNCTION public.get_document_templates() RESET search_path;
ALTER FUNCTION public.get_duplicate_contacts() RESET search_path;
ALTER FUNCTION public.get_employee_page_access(p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_feature_flags() RESET search_path;
ALTER FUNCTION public.get_insurance_carriers() RESET search_path;
ALTER FUNCTION public.get_job_contacts(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_job_equipment(p_job_id uuid, p_include_removed boolean) RESET search_path;
ALTER FUNCTION public.get_job_labor_summary(p_job_id uuid, p_start_date date, p_end_date date) RESET search_path;
ALTER FUNCTION public.get_job_readings(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_job_rooms(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_job_schedule(p_job_schedule_id uuid) RESET search_path;
ALTER FUNCTION public.get_job_schedules(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_job_task_pool(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_job_task_summary(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_message_log(p_limit integer, p_offset integer, p_direction text, p_status text) RESET search_path;
ALTER FUNCTION public.get_my_appointments_today(p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_orphan_contacts() RESET search_path;
ALTER FUNCTION public.get_payroll_summary(p_start_date date, p_end_date date) RESET search_path;
ALTER FUNCTION public.get_referral_sources() RESET search_path;
ALTER FUNCTION public.get_schedule_template(p_template_id uuid) RESET search_path;
ALTER FUNCTION public.get_schedule_templates(p_division text) RESET search_path;
ALTER FUNCTION public.get_scheduled_queue(p_limit integer) RESET search_path;
ALTER FUNCTION public.get_sign_request_by_token(p_token text) RESET search_path;
ALTER FUNCTION public.get_stalled_materials(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_stalled_materials_for_employee(p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_table_stats(p_table text) RESET search_path;
ALTER FUNCTION public.get_tasks_for_appointment(p_appointment_id uuid) RESET search_path;
ALTER FUNCTION public.get_tech_claims(p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_tech_feedback() RESET search_path;
ALTER FUNCTION public.get_tech_status_board() RESET search_path;
ALTER FUNCTION public.get_timesheet_entries(p_start_date date, p_end_date date, p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.get_unassigned_tasks(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_water_loss_report_data(p_job_id uuid) RESET search_path;
ALTER FUNCTION public.get_worker_runs(p_limit integer) RESET search_path;
ALTER FUNCTION public.insert_job_document(p_job_id uuid, p_name text, p_file_path text, p_mime_type text, p_category text, p_uploaded_by uuid, p_appointment_id uuid, p_description text, p_room_id uuid) RESET search_path;
ALTER FUNCTION public.insert_reading(p_job_id uuid, p_room_id uuid, p_material material_type, p_location text, p_mc numeric, p_rh numeric, p_temp_f numeric, p_gpp numeric, p_dew_point numeric, p_is_affected boolean, p_equipment_id uuid, p_taken_by uuid, p_notes text, p_client_id uuid, p_taken_at timestamp with time zone) RESET search_path;
ALTER FUNCTION public.insert_tech_feedback(p_employee_id uuid, p_type text, p_title text, p_description text, p_screenshots jsonb) RESET search_path;
ALTER FUNCTION public.link_contact_to_job(p_contact_id uuid, p_job_id uuid, p_role text, p_is_primary boolean, p_notes text) RESET search_path;
ALTER FUNCTION public.log_system_event(p_event_type text, p_entity_type text, p_entity_id uuid, p_job_id uuid, p_actor_id uuid, p_payload jsonb) RESET search_path;
ALTER FUNCTION public.merge_claims(p_keep_id uuid, p_merge_id uuid) RESET search_path;
ALTER FUNCTION public.merge_contacts(p_keep_id uuid, p_merge_id uuid) RESET search_path;
ALTER FUNCTION public.merge_jobs(p_keep_id uuid, p_merge_id uuid) RESET search_path;
ALTER FUNCTION public.move_photo_to_room(p_document_id uuid, p_room_id uuid) RESET search_path;
ALTER FUNCTION public.place_equipment(p_job_id uuid, p_room_id uuid, p_equipment_type equipment_type, p_nickname text, p_serial text, p_placed_by uuid, p_client_id uuid, p_notes text) RESET search_path;
ALTER FUNCTION public.preview_schedule(p_template_id uuid, p_start_date date, p_skip_weekends boolean, p_duration_overrides jsonb) RESET search_path;
ALTER FUNCTION public.record_email_open(p_token uuid) RESET search_path;
ALTER FUNCTION public.remove_equipment(p_equipment_id uuid, p_removed_by uuid) RESET search_path;
ALTER FUNCTION public.search_contacts_for_job(p_query text) RESET search_path;
ALTER FUNCTION public.sync_job_to_claim() RESET search_path;
ALTER FUNCTION public.toggle_appointment_task(p_task_id uuid, p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.toggle_job_task(p_task_id uuid, p_employee_id uuid) RESET search_path;
ALTER FUNCTION public.trigger_document_events() RESET search_path;
ALTER FUNCTION public.trigger_message_events() RESET search_path;
ALTER FUNCTION public.update_appointment(p_appointment_id uuid, p_date date, p_time_start time without time zone, p_time_end time without time zone, p_title text, p_type text, p_status text, p_notes text) RESET search_path;
ALTER FUNCTION public.update_reading(p_reading_id uuid, p_material material_type, p_location text, p_mc numeric, p_rh numeric, p_temp_f numeric, p_gpp numeric, p_dew_point numeric, p_is_affected boolean, p_notes text, p_edited_by uuid) RESET search_path;
ALTER FUNCTION public.update_room(p_room_id uuid, p_name text, p_area_sqft numeric, p_ceiling_height_ft numeric, p_sort_order integer) RESET search_path;
ALTER FUNCTION public.update_tech_feedback(p_id uuid, p_status text, p_admin_notes text) RESET search_path;
ALTER FUNCTION public.upsert_appointment_task(p_id uuid, p_appointment_id uuid, p_title text, p_description text, p_is_required boolean, p_display_order integer) RESET search_path;
ALTER FUNCTION public.upsert_contact_address(p_contact_id uuid, p_address_id uuid, p_label text, p_address text, p_city text, p_state text, p_zip text, p_is_billing boolean, p_notes text) RESET search_path;
ALTER FUNCTION public.upsert_document_template(p_doc_type text, p_division text, p_heading text, p_body text, p_sort_order integer) RESET search_path;
ALTER FUNCTION public.upsert_employee_page_access(p_employee_id uuid, p_nav_key text, p_can_view boolean, p_updated_by uuid) RESET search_path;
ALTER FUNCTION public.upsert_feature_flag(p_key text, p_enabled boolean, p_dev_only_user_id uuid, p_category text, p_label text, p_description text, p_updated_by uuid) RESET search_path;
ALTER FUNCTION public.upsert_feature_flag(p_key text, p_enabled boolean, p_dev_only_user_id uuid, p_category text, p_label text, p_description text, p_updated_by uuid, p_force_disabled boolean) RESET search_path;
ALTER FUNCTION public.upsert_insurance_carrier(p_id uuid, p_name text, p_short_name text, p_sort_order integer) RESET search_path;
ALTER FUNCTION public.upsert_permission(p_role text, p_nav_key text, p_can_view boolean, p_can_edit boolean) RESET search_path;
ALTER FUNCTION public.upsert_referral_source(p_id uuid, p_name text, p_category text, p_sort_order integer) RESET search_path;
ALTER FUNCTION public.upsert_time_entry(p_id uuid, p_job_id uuid, p_employee_id uuid, p_work_date date, p_hours numeric, p_work_type text, p_description text, p_notes text) RESET search_path;

-- Storage policies
DROP POLICY IF EXISTS "Auth insert message-attachments" ON storage.objects;
DROP POLICY IF EXISTS "Public read message-attachments" ON storage.objects;
DROP POLICY IF EXISTS anon_delete_job_files ON storage.objects;
DROP POLICY IF EXISTS anon_read_job_files ON storage.objects;
DROP POLICY IF EXISTS anon_upload_job_files ON storage.objects;
DROP POLICY IF EXISTS job_files_delete ON storage.objects;
DROP POLICY IF EXISTS job_files_insert ON storage.objects;
DROP POLICY IF EXISTS job_files_select ON storage.objects;
DROP POLICY IF EXISTS message_attachments_delete ON storage.objects;
DROP POLICY IF EXISTS message_attachments_insert ON storage.objects;
DROP POLICY IF EXISTS message_attachments_select ON storage.objects;
CREATE POLICY "Auth insert message-attachments" ON storage.objects AS PERMISSIVE FOR INSERT TO public WITH CHECK ((bucket_id = 'message-attachments'::text));
CREATE POLICY "Public read message-attachments" ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'message-attachments'::text));
CREATE POLICY anon_delete_job_files ON storage.objects AS PERMISSIVE FOR DELETE TO anon USING ((bucket_id = 'job-files'::text));
CREATE POLICY anon_read_job_files ON storage.objects AS PERMISSIVE FOR SELECT TO anon USING ((bucket_id = 'job-files'::text));
CREATE POLICY anon_upload_job_files ON storage.objects AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((bucket_id = 'job-files'::text));
CREATE POLICY job_files_delete ON storage.objects AS PERMISSIVE FOR DELETE TO public USING ((bucket_id = 'job-files'::text));
CREATE POLICY job_files_insert ON storage.objects AS PERMISSIVE FOR INSERT TO public WITH CHECK ((bucket_id = 'job-files'::text));
CREATE POLICY job_files_select ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'job-files'::text));
CREATE POLICY message_attachments_delete ON storage.objects AS PERMISSIVE FOR DELETE TO public USING ((bucket_id = 'message-attachments'::text));
CREATE POLICY message_attachments_insert ON storage.objects AS PERMISSIVE FOR INSERT TO public WITH CHECK ((bucket_id = 'message-attachments'::text));
CREATE POLICY message_attachments_select ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'message-attachments'::text));
COMMIT;
