-- ════════════════════════════════════════════════════════════════════════════════
-- 20260708_dbf_p3_anon_policy_closure.sql
-- DB-Foundation Phase P3 (anon closure) — recreate public-schema policies WITHOUT anon  [item ③/⑤]
--   docs/db-foundation-roadmap.md → Phase P3; database-standard.md §1–§2; ownership manifest §8.
--
-- ⚠️ RED-TIER (database-standard §5 + roadmap autonomy ledger): this REVOKES the anonymous
--   browser role's access to ~120 public tables. Staged for the owner's apply window; it must
--   apply ONLY AFTER the SignPage code change + get_sign_document_templates RPC are LIVE
--   (Cloudflare deploy of this PR), because it removes SignPage's former direct anon read of
--   document_templates. One shared Supabase backs dev + prod — live in both on apply.
--
-- WHAT THIS DOES (plain language):
--   Every one of these tables had a policy that let the anonymous (logged-out) browser role
--   read/write it. The app actually runs as `authenticated` (a real Supabase JWT — see
--   database-standard preamble), so this drops each anon policy and recreates it IDENTICALLY
--   scoped to `authenticated` only. No logged-in behavior changes; workers use service_role
--   and are unaffected; the logged-out attack surface (the anon key ships in the JS bundle)
--   closes. Generated from the LIVE catalog (161 anon policies / 85 tables), minus the
--   database-standard §2 allowlist and the ownership-manifest §8 deferred-hardening tables.
--
-- IDEMPOTENT + ALPHABETICAL: each table's block is DROP POLICY IF EXISTS → CREATE, ordered by
--   table then policy name, so a partial apply is safely re-runnable (database-standard §5
--   chunking intent). Policy DDL takes only a brief metadata lock — no table rewrite.
--
-- KEPT ANON (database-standard §2 allowlist — deliberately NOT in this file):
--   • employees.allow_anon_read_employees, feature_flags.anon_read_flags,
--     employee_page_access.anon_read_employee_page_access — login/devLogin session bootstrap
--     reads (kept verbatim). nav_permissions is NARROWED below (anon ALL → anon SELECT).
--   • document_templates anon read is retired in favor of get_sign_document_templates() — both
--     its policies convert to authenticated here.
--
-- DEFERRED (ownership manifest §8 — NOT touched; re-check when the owning phase merges):
--   messages, conversations, conversation_participants, email_campaigns,
--   email_campaign_recipients, email_campaign_exclusions, email_suppressions (omni);
--   crm_automations, crm_automation_runs, jobs, job_phase_history (5-Ops); appointments,
--   claims, contacts (schedule); automation_settings (CRM 4b). These keep anon this phase.
--
-- ROLLBACK: see the fully-commented "-- ROLLBACK" block at the foot of this file (restores the
--   exact prior anon policies). Also committed as a standalone reference in the P3 PR body.
-- ═════════════════════════════════════════════════════════════════════════════════

DROP POLICY IF EXISTS ad_spend_all ON public.ad_spend;
CREATE POLICY ad_spend_all ON public.ad_spend FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS all_delete_appointment_crew ON public.appointment_crew;
CREATE POLICY all_delete_appointment_crew ON public.appointment_crew FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS all_insert_appointment_crew ON public.appointment_crew;
CREATE POLICY all_insert_appointment_crew ON public.appointment_crew FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS all_select_appointment_crew ON public.appointment_crew;
CREATE POLICY all_select_appointment_crew ON public.appointment_crew FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS all_update_appointment_crew ON public.appointment_crew;
CREATE POLICY all_update_appointment_crew ON public.appointment_crew FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS appointment_dependencies_delete ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_delete ON public.appointment_dependencies FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS appointment_dependencies_insert ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_insert ON public.appointment_dependencies FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS appointment_dependencies_select ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_select ON public.appointment_dependencies FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS appointment_dependencies_update ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_update ON public.appointment_dependencies FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_delete_automation_rules ON public.automation_rules;
CREATE POLICY anon_delete_automation_rules ON public.automation_rules FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_automation_rules ON public.automation_rules;
CREATE POLICY anon_insert_automation_rules ON public.automation_rules FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_automation_rules ON public.automation_rules;
CREATE POLICY anon_select_automation_rules ON public.automation_rules FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_automation_rules ON public.automation_rules;
CREATE POLICY anon_update_automation_rules ON public.automation_rules FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_campaigns ON public.campaigns;
CREATE POLICY allow_anon_read_campaigns ON public.campaigns FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS ca_delete ON public.contact_addresses;
CREATE POLICY ca_delete ON public.contact_addresses FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS ca_insert ON public.contact_addresses;
CREATE POLICY ca_insert ON public.contact_addresses FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS ca_select ON public.contact_addresses;
CREATE POLICY ca_select ON public.contact_addresses FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS ca_update ON public.contact_addresses;
CREATE POLICY ca_update ON public.contact_addresses FOR UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS contact_jobs_anon_delete ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_delete ON public.contact_jobs FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS contact_jobs_anon_insert ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_insert ON public.contact_jobs FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS contact_jobs_anon_select ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_select ON public.contact_jobs FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS contact_jobs_anon_update ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_update ON public.contact_jobs FOR UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS crm_build_phases_all ON public.crm_build_phases;
CREATE POLICY crm_build_phases_all ON public.crm_build_phases FOR ALL TO authenticated USING ((NOT is_crm_partner(auth.uid()))) WITH CHECK ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS crm_build_stages_all ON public.crm_build_stages;
CREATE POLICY crm_build_stages_all ON public.crm_build_stages FOR ALL TO authenticated USING ((NOT is_crm_partner(auth.uid()))) WITH CHECK ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS crm_import_batches_all ON public.crm_import_batches;
CREATE POLICY crm_import_batches_all ON public.crm_import_batches FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_orgs_all ON public.crm_orgs;
CREATE POLICY crm_orgs_all ON public.crm_orgs FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_segments_all ON public.crm_segments;
CREATE POLICY crm_segments_all ON public.crm_segments FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_sequence_enrollments_all ON public.crm_sequence_enrollments;
CREATE POLICY crm_sequence_enrollments_all ON public.crm_sequence_enrollments FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_sequence_steps_all ON public.crm_sequence_steps;
CREATE POLICY crm_sequence_steps_all ON public.crm_sequence_steps FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_sequences_all ON public.crm_sequences;
CREATE POLICY crm_sequences_all ON public.crm_sequences FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_tasks_all ON public.crm_tasks;
CREATE POLICY crm_tasks_all ON public.crm_tasks FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_tracking_numbers_all ON public.crm_tracking_numbers;
CREATE POLICY crm_tracking_numbers_all ON public.crm_tracking_numbers FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS demo_sheet_schemas_all ON public.demo_sheet_schemas;
CREATE POLICY demo_sheet_schemas_all ON public.demo_sheet_schemas FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Own tokens or admin read" ON public.device_tokens;
CREATE POLICY "Own tokens or admin read" ON public.device_tokens FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS dispatch_board_jobs_delete ON public.dispatch_board_jobs;
CREATE POLICY dispatch_board_jobs_delete ON public.dispatch_board_jobs FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS dispatch_board_jobs_insert ON public.dispatch_board_jobs;
CREATE POLICY dispatch_board_jobs_insert ON public.dispatch_board_jobs FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS dispatch_board_jobs_select ON public.dispatch_board_jobs;
CREATE POLICY dispatch_board_jobs_select ON public.dispatch_board_jobs FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "anon read document_templates" ON public.document_templates;
CREATE POLICY "anon read document_templates" ON public.document_templates FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "anon write document_templates" ON public.document_templates;
CREATE POLICY "anon write document_templates" ON public.document_templates FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS equip_authenticated_all ON public.equipment_placements;
CREATE POLICY equip_authenticated_all ON public.equipment_placements FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS form_definition_versions_all ON public.form_definition_versions;
CREATE POLICY form_definition_versions_all ON public.form_definition_versions FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS form_definitions_all ON public.form_definitions;
CREATE POLICY form_definitions_all ON public.form_definitions FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS form_submissions_all ON public.form_submissions;
CREATE POLICY form_submissions_all ON public.form_submissions FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS inbound_leads_all ON public.inbound_leads;
CREATE POLICY inbound_leads_all ON public.inbound_leads FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_carriers ON public.insurance_carriers;
CREATE POLICY anon_read_carriers ON public.insurance_carriers FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_write_insurance_carriers ON public.insurance_carriers;
CREATE POLICY anon_write_insurance_carriers ON public.insurance_carriers FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_invoices ON public.invoices;
CREATE POLICY allow_anon_read_invoices ON public.invoices FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_delete_job_documents ON public.job_documents;
CREATE POLICY anon_delete_job_documents ON public.job_documents FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_job_documents ON public.job_documents;
CREATE POLICY anon_insert_job_documents ON public.job_documents FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_job_documents ON public.job_documents;
CREATE POLICY anon_select_job_documents ON public.job_documents FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_job_documents ON public.job_documents;
CREATE POLICY anon_update_job_documents ON public.job_documents FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_delete_job_notes ON public.job_notes;
CREATE POLICY anon_delete_job_notes ON public.job_notes FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_job_notes ON public.job_notes;
CREATE POLICY anon_insert_job_notes ON public.job_notes FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_job_notes ON public.job_notes;
CREATE POLICY anon_select_job_notes ON public.job_notes FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_job_notes ON public.job_notes;
CREATE POLICY anon_update_job_notes ON public.job_notes FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS job_number_sequences_insert ON public.job_number_sequences;
CREATE POLICY job_number_sequences_insert ON public.job_number_sequences FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS job_number_sequences_select ON public.job_number_sequences;
CREATE POLICY job_number_sequences_select ON public.job_number_sequences FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS job_number_sequences_update ON public.job_number_sequences;
CREATE POLICY job_number_sequences_update ON public.job_number_sequences FOR UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS allow_anon_read_phases ON public.job_phases;
CREATE POLICY allow_anon_read_phases ON public.job_phases FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_delete_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_delete_job_schedule_phases ON public.job_schedule_phases FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_insert_job_schedule_phases ON public.job_schedule_phases FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_read_job_schedule_phases ON public.job_schedule_phases FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_update_job_schedule_phases ON public.job_schedule_phases FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS job_schedules_delete ON public.job_schedules;
CREATE POLICY job_schedules_delete ON public.job_schedules FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS job_schedules_insert ON public.job_schedules;
CREATE POLICY job_schedules_insert ON public.job_schedules FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS job_schedules_select ON public.job_schedules;
CREATE POLICY job_schedules_select ON public.job_schedules FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS job_schedules_update ON public.job_schedules;
CREATE POLICY job_schedules_update ON public.job_schedules FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_all ON public.job_supplements;
CREATE POLICY anon_all ON public.job_supplements FOR ALL TO authenticated USING ((NOT is_crm_partner(auth.uid()))) WITH CHECK ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS job_tasks_delete ON public.job_tasks;
CREATE POLICY job_tasks_delete ON public.job_tasks FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS job_tasks_insert ON public.job_tasks;
CREATE POLICY job_tasks_insert ON public.job_tasks FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS job_tasks_select ON public.job_tasks;
CREATE POLICY job_tasks_select ON public.job_tasks FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS job_tasks_update ON public.job_tasks;
CREATE POLICY job_tasks_update ON public.job_tasks FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS jte_select_all ON public.job_time_entries;
CREATE POLICY jte_select_all ON public.job_time_entries FOR SELECT TO authenticated USING ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS lead_attribution_all ON public.lead_attribution;
CREATE POLICY lead_attribution_all ON public.lead_attribution FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS lead_pipeline_stage_all ON public.lead_pipeline_stage;
CREATE POLICY lead_pipeline_stage_all ON public.lead_pipeline_stage FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS lead_score_factors_all ON public.lead_score_factors;
CREATE POLICY lead_score_factors_all ON public.lead_score_factors FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS lead_stage_history_all ON public.lead_stage_history;
CREATE POLICY lead_stage_history_all ON public.lead_stage_history FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_templates ON public.message_templates;
CREATE POLICY allow_anon_read_templates ON public.message_templates FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS moisture_authenticated_all ON public.moisture_readings;
CREATE POLICY moisture_authenticated_all ON public.moisture_readings FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_employee_overrides_all ON public.notification_employee_overrides;
CREATE POLICY notification_employee_overrides_all ON public.notification_employee_overrides FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_prefs_all ON public.notification_prefs;
CREATE POLICY notification_prefs_all ON public.notification_prefs FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_insert_notification_queue ON public.notification_queue;
CREATE POLICY anon_insert_notification_queue ON public.notification_queue FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_notification_queue ON public.notification_queue;
CREATE POLICY anon_select_notification_queue ON public.notification_queue FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_notification_queue ON public.notification_queue;
CREATE POLICY anon_update_notification_queue ON public.notification_queue FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_role_defaults_all ON public.notification_role_defaults;
CREATE POLICY notification_role_defaults_all ON public.notification_role_defaults FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_types_all ON public.notification_types;
CREATE POLICY notification_types_all ON public.notification_types FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notifications_delete_testrows ON public.notifications;
CREATE POLICY notifications_delete_testrows ON public.notifications FOR DELETE TO authenticated USING ((type = '__f2test__'::text));
DROP POLICY IF EXISTS allow_anon_delete_payments ON public.payments;
CREATE POLICY allow_anon_delete_payments ON public.payments FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS allow_anon_insert_payments ON public.payments;
CREATE POLICY allow_anon_insert_payments ON public.payments FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_select_payments ON public.payments;
CREATE POLICY allow_anon_select_payments ON public.payments FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS allow_anon_update_payments ON public.payments;
CREATE POLICY allow_anon_update_payments ON public.payments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS pipeline_stages_all ON public.pipeline_stages;
CREATE POLICY pipeline_stages_all ON public.pipeline_stages FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS property_meld_melds_all ON public.property_meld_melds;
CREATE POLICY property_meld_melds_all ON public.property_meld_melds FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_referral_sources ON public.referral_sources;
CREATE POLICY anon_read_referral_sources ON public.referral_sources FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_write_referral_sources ON public.referral_sources;
CREATE POLICY anon_write_referral_sources ON public.referral_sources FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS rooms_authenticated_all ON public.rooms;
CREATE POLICY rooms_authenticated_all ON public.rooms FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_schedule_blocks ON public.schedule_blocks;
CREATE POLICY allow_anon_read_schedule_blocks ON public.schedule_blocks FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS schedule_templates_delete ON public.schedule_templates;
CREATE POLICY schedule_templates_delete ON public.schedule_templates FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS schedule_templates_insert ON public.schedule_templates;
CREATE POLICY schedule_templates_insert ON public.schedule_templates FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS schedule_templates_select ON public.schedule_templates;
CREATE POLICY schedule_templates_select ON public.schedule_templates FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS schedule_templates_update ON public.schedule_templates;
CREATE POLICY schedule_templates_update ON public.schedule_templates FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_insert_scheduled_messages ON public.scheduled_messages;
CREATE POLICY allow_anon_insert_scheduled_messages ON public.scheduled_messages FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_scheduled_messages ON public.scheduled_messages;
CREATE POLICY allow_anon_read_scheduled_messages ON public.scheduled_messages FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_sign_requests ON public.sign_requests;
CREATE POLICY anon_insert_sign_requests ON public.sign_requests FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_sign_requests ON public.sign_requests;
CREATE POLICY anon_select_sign_requests ON public.sign_requests FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_sign_requests ON public.sign_requests;
CREATE POLICY anon_update_sign_requests ON public.sign_requests FOR UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS allow_anon_insert_consent_log ON public.sms_consent_log;
CREATE POLICY allow_anon_insert_consent_log ON public.sms_consent_log FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_consent_log ON public.sms_consent_log;
CREATE POLICY allow_anon_read_consent_log ON public.sms_consent_log FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS tech_feedback_all ON public.tech_feedback;
CREATE POLICY tech_feedback_all ON public.tech_feedback FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS template_dependencies_delete ON public.template_dependencies;
CREATE POLICY template_dependencies_delete ON public.template_dependencies FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS template_dependencies_insert ON public.template_dependencies;
CREATE POLICY template_dependencies_insert ON public.template_dependencies FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS template_dependencies_select ON public.template_dependencies;
CREATE POLICY template_dependencies_select ON public.template_dependencies FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS template_dependencies_update ON public.template_dependencies;
CREATE POLICY template_dependencies_update ON public.template_dependencies FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS template_phases_delete ON public.template_phases;
CREATE POLICY template_phases_delete ON public.template_phases FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS template_phases_insert ON public.template_phases;
CREATE POLICY template_phases_insert ON public.template_phases FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS template_phases_select ON public.template_phases;
CREATE POLICY template_phases_select ON public.template_phases FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS template_phases_update ON public.template_phases;
CREATE POLICY template_phases_update ON public.template_phases FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS template_tasks_delete ON public.template_tasks;
CREATE POLICY template_tasks_delete ON public.template_tasks FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS template_tasks_insert ON public.template_tasks;
CREATE POLICY template_tasks_insert ON public.template_tasks FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS template_tasks_select ON public.template_tasks;
CREATE POLICY template_tasks_select ON public.template_tasks FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS template_tasks_update ON public.template_tasks;
CREATE POLICY template_tasks_update ON public.template_tasks FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS tecr_read ON public.time_entry_change_requests;
CREATE POLICY tecr_read ON public.time_entry_change_requests FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS ted_read ON public.time_entry_deletions;
CREATE POLICY ted_read ON public.time_entry_deletions FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_worker_runs ON public.worker_runs;
CREATE POLICY anon_insert_worker_runs ON public.worker_runs FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_worker_runs ON public.worker_runs;
CREATE POLICY anon_read_worker_runs ON public.worker_runs FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS anon_update_worker_runs ON public.worker_runs;
CREATE POLICY anon_update_worker_runs ON public.worker_runs FOR UPDATE TO authenticated USING (true);

-- ─── nav_permissions — NARROW anon ALL → anon SELECT (§2 allowlist covers reads only) ───
-- Login/devLogin bootstrap reads role nav via anon; anon never needs write/delete here.
-- authenticated keeps full access via the untouched nav_permissions_auth_all policy.
DROP POLICY IF EXISTS nav_permissions_anon_all ON public.nav_permissions;
DROP POLICY IF EXISTS nav_permissions_anon_read ON public.nav_permissions;
CREATE POLICY nav_permissions_anon_read ON public.nav_permissions FOR SELECT TO anon USING (true);

-- ─── notifications_select — ALTER to authenticated (never DROP: realtime + reads depend on it) ───
ALTER POLICY notifications_select ON public.notifications TO authenticated;


-- ═══ ROLLBACK (re-open anon — restores the exact pre-P3 policies) ═══
-- Run this block to fully revert this migration.
/*
DROP POLICY IF EXISTS ad_spend_all ON public.ad_spend;
CREATE POLICY ad_spend_all ON public.ad_spend FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS all_delete_appointment_crew ON public.appointment_crew;
CREATE POLICY all_delete_appointment_crew ON public.appointment_crew FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS all_insert_appointment_crew ON public.appointment_crew;
CREATE POLICY all_insert_appointment_crew ON public.appointment_crew FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS all_select_appointment_crew ON public.appointment_crew;
CREATE POLICY all_select_appointment_crew ON public.appointment_crew FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS all_update_appointment_crew ON public.appointment_crew;
CREATE POLICY all_update_appointment_crew ON public.appointment_crew FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS appointment_dependencies_delete ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_delete ON public.appointment_dependencies FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS appointment_dependencies_insert ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_insert ON public.appointment_dependencies FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS appointment_dependencies_select ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_select ON public.appointment_dependencies FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS appointment_dependencies_update ON public.appointment_dependencies;
CREATE POLICY appointment_dependencies_update ON public.appointment_dependencies FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_delete_automation_rules ON public.automation_rules;
CREATE POLICY anon_delete_automation_rules ON public.automation_rules FOR DELETE TO anon USING (true);
DROP POLICY IF EXISTS anon_insert_automation_rules ON public.automation_rules;
CREATE POLICY anon_insert_automation_rules ON public.automation_rules FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_automation_rules ON public.automation_rules;
CREATE POLICY anon_select_automation_rules ON public.automation_rules FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_update_automation_rules ON public.automation_rules;
CREATE POLICY anon_update_automation_rules ON public.automation_rules FOR UPDATE TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_campaigns ON public.campaigns;
CREATE POLICY allow_anon_read_campaigns ON public.campaigns FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS ca_delete ON public.contact_addresses;
CREATE POLICY ca_delete ON public.contact_addresses FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS ca_insert ON public.contact_addresses;
CREATE POLICY ca_insert ON public.contact_addresses FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS ca_select ON public.contact_addresses;
CREATE POLICY ca_select ON public.contact_addresses FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS ca_update ON public.contact_addresses;
CREATE POLICY ca_update ON public.contact_addresses FOR UPDATE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS contact_jobs_anon_delete ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_delete ON public.contact_jobs FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS contact_jobs_anon_insert ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_insert ON public.contact_jobs FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS contact_jobs_anon_select ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_select ON public.contact_jobs FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS contact_jobs_anon_update ON public.contact_jobs;
CREATE POLICY contact_jobs_anon_update ON public.contact_jobs FOR UPDATE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS crm_build_phases_all ON public.crm_build_phases;
CREATE POLICY crm_build_phases_all ON public.crm_build_phases FOR ALL TO anon, authenticated USING ((NOT is_crm_partner(auth.uid()))) WITH CHECK ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS crm_build_stages_all ON public.crm_build_stages;
CREATE POLICY crm_build_stages_all ON public.crm_build_stages FOR ALL TO anon, authenticated USING ((NOT is_crm_partner(auth.uid()))) WITH CHECK ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS crm_import_batches_all ON public.crm_import_batches;
CREATE POLICY crm_import_batches_all ON public.crm_import_batches FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_orgs_all ON public.crm_orgs;
CREATE POLICY crm_orgs_all ON public.crm_orgs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_segments_all ON public.crm_segments;
CREATE POLICY crm_segments_all ON public.crm_segments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_sequence_enrollments_all ON public.crm_sequence_enrollments;
CREATE POLICY crm_sequence_enrollments_all ON public.crm_sequence_enrollments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_sequence_steps_all ON public.crm_sequence_steps;
CREATE POLICY crm_sequence_steps_all ON public.crm_sequence_steps FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_sequences_all ON public.crm_sequences;
CREATE POLICY crm_sequences_all ON public.crm_sequences FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_tasks_all ON public.crm_tasks;
CREATE POLICY crm_tasks_all ON public.crm_tasks FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS crm_tracking_numbers_all ON public.crm_tracking_numbers;
CREATE POLICY crm_tracking_numbers_all ON public.crm_tracking_numbers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS demo_sheet_schemas_all ON public.demo_sheet_schemas;
CREATE POLICY demo_sheet_schemas_all ON public.demo_sheet_schemas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Own tokens or admin read" ON public.device_tokens;
CREATE POLICY "Own tokens or admin read" ON public.device_tokens FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS dispatch_board_jobs_delete ON public.dispatch_board_jobs;
CREATE POLICY dispatch_board_jobs_delete ON public.dispatch_board_jobs FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS dispatch_board_jobs_insert ON public.dispatch_board_jobs;
CREATE POLICY dispatch_board_jobs_insert ON public.dispatch_board_jobs FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS dispatch_board_jobs_select ON public.dispatch_board_jobs;
CREATE POLICY dispatch_board_jobs_select ON public.dispatch_board_jobs FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon read document_templates" ON public.document_templates;
CREATE POLICY "anon read document_templates" ON public.document_templates FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon write document_templates" ON public.document_templates;
CREATE POLICY "anon write document_templates" ON public.document_templates FOR ALL TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS equip_authenticated_all ON public.equipment_placements;
CREATE POLICY equip_authenticated_all ON public.equipment_placements FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS form_definition_versions_all ON public.form_definition_versions;
CREATE POLICY form_definition_versions_all ON public.form_definition_versions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS form_definitions_all ON public.form_definitions;
CREATE POLICY form_definitions_all ON public.form_definitions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS form_submissions_all ON public.form_submissions;
CREATE POLICY form_submissions_all ON public.form_submissions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS inbound_leads_all ON public.inbound_leads;
CREATE POLICY inbound_leads_all ON public.inbound_leads FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_carriers ON public.insurance_carriers;
CREATE POLICY anon_read_carriers ON public.insurance_carriers FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_write_insurance_carriers ON public.insurance_carriers;
CREATE POLICY anon_write_insurance_carriers ON public.insurance_carriers FOR ALL TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_invoices ON public.invoices;
CREATE POLICY allow_anon_read_invoices ON public.invoices FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_delete_job_documents ON public.job_documents;
CREATE POLICY anon_delete_job_documents ON public.job_documents FOR DELETE TO anon USING (true);
DROP POLICY IF EXISTS anon_insert_job_documents ON public.job_documents;
CREATE POLICY anon_insert_job_documents ON public.job_documents FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_job_documents ON public.job_documents;
CREATE POLICY anon_select_job_documents ON public.job_documents FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_update_job_documents ON public.job_documents;
CREATE POLICY anon_update_job_documents ON public.job_documents FOR UPDATE TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_delete_job_notes ON public.job_notes;
CREATE POLICY anon_delete_job_notes ON public.job_notes FOR DELETE TO anon USING (true);
DROP POLICY IF EXISTS anon_insert_job_notes ON public.job_notes;
CREATE POLICY anon_insert_job_notes ON public.job_notes FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_job_notes ON public.job_notes;
CREATE POLICY anon_select_job_notes ON public.job_notes FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_update_job_notes ON public.job_notes;
CREATE POLICY anon_update_job_notes ON public.job_notes FOR UPDATE TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS job_number_sequences_insert ON public.job_number_sequences;
CREATE POLICY job_number_sequences_insert ON public.job_number_sequences FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS job_number_sequences_select ON public.job_number_sequences;
CREATE POLICY job_number_sequences_select ON public.job_number_sequences FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS job_number_sequences_update ON public.job_number_sequences;
CREATE POLICY job_number_sequences_update ON public.job_number_sequences FOR UPDATE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS allow_anon_read_phases ON public.job_phases;
CREATE POLICY allow_anon_read_phases ON public.job_phases FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_delete_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_delete_job_schedule_phases ON public.job_schedule_phases FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_insert_job_schedule_phases ON public.job_schedule_phases FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_read_job_schedule_phases ON public.job_schedule_phases FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS anon_update_job_schedule_phases ON public.job_schedule_phases;
CREATE POLICY anon_update_job_schedule_phases ON public.job_schedule_phases FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS job_schedules_delete ON public.job_schedules;
CREATE POLICY job_schedules_delete ON public.job_schedules FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS job_schedules_insert ON public.job_schedules;
CREATE POLICY job_schedules_insert ON public.job_schedules FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS job_schedules_select ON public.job_schedules;
CREATE POLICY job_schedules_select ON public.job_schedules FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS job_schedules_update ON public.job_schedules;
CREATE POLICY job_schedules_update ON public.job_schedules FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_all ON public.job_supplements;
CREATE POLICY anon_all ON public.job_supplements FOR ALL TO anon, authenticated USING ((NOT is_crm_partner(auth.uid()))) WITH CHECK ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS job_tasks_delete ON public.job_tasks;
CREATE POLICY job_tasks_delete ON public.job_tasks FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS job_tasks_insert ON public.job_tasks;
CREATE POLICY job_tasks_insert ON public.job_tasks FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS job_tasks_select ON public.job_tasks;
CREATE POLICY job_tasks_select ON public.job_tasks FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS job_tasks_update ON public.job_tasks;
CREATE POLICY job_tasks_update ON public.job_tasks FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS jte_select_all ON public.job_time_entries;
CREATE POLICY jte_select_all ON public.job_time_entries FOR SELECT TO anon, authenticated USING ((NOT is_crm_partner(auth.uid())));
DROP POLICY IF EXISTS lead_attribution_all ON public.lead_attribution;
CREATE POLICY lead_attribution_all ON public.lead_attribution FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS lead_pipeline_stage_all ON public.lead_pipeline_stage;
CREATE POLICY lead_pipeline_stage_all ON public.lead_pipeline_stage FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS lead_score_factors_all ON public.lead_score_factors;
CREATE POLICY lead_score_factors_all ON public.lead_score_factors FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS lead_stage_history_all ON public.lead_stage_history;
CREATE POLICY lead_stage_history_all ON public.lead_stage_history FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_templates ON public.message_templates;
CREATE POLICY allow_anon_read_templates ON public.message_templates FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS moisture_authenticated_all ON public.moisture_readings;
CREATE POLICY moisture_authenticated_all ON public.moisture_readings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_employee_overrides_all ON public.notification_employee_overrides;
CREATE POLICY notification_employee_overrides_all ON public.notification_employee_overrides FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_prefs_all ON public.notification_prefs;
CREATE POLICY notification_prefs_all ON public.notification_prefs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_insert_notification_queue ON public.notification_queue;
CREATE POLICY anon_insert_notification_queue ON public.notification_queue FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_notification_queue ON public.notification_queue;
CREATE POLICY anon_select_notification_queue ON public.notification_queue FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_update_notification_queue ON public.notification_queue;
CREATE POLICY anon_update_notification_queue ON public.notification_queue FOR UPDATE TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_role_defaults_all ON public.notification_role_defaults;
CREATE POLICY notification_role_defaults_all ON public.notification_role_defaults FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notification_types_all ON public.notification_types;
CREATE POLICY notification_types_all ON public.notification_types FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS notifications_delete_testrows ON public.notifications;
CREATE POLICY notifications_delete_testrows ON public.notifications FOR DELETE TO anon, authenticated USING ((type = '__f2test__'::text));
DROP POLICY IF EXISTS allow_anon_delete_payments ON public.payments;
CREATE POLICY allow_anon_delete_payments ON public.payments FOR DELETE TO anon USING (true);
DROP POLICY IF EXISTS allow_anon_insert_payments ON public.payments;
CREATE POLICY allow_anon_insert_payments ON public.payments FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_select_payments ON public.payments;
CREATE POLICY allow_anon_select_payments ON public.payments FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS allow_anon_update_payments ON public.payments;
CREATE POLICY allow_anon_update_payments ON public.payments FOR UPDATE TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS pipeline_stages_all ON public.pipeline_stages;
CREATE POLICY pipeline_stages_all ON public.pipeline_stages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS property_meld_melds_all ON public.property_meld_melds;
CREATE POLICY property_meld_melds_all ON public.property_meld_melds FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_referral_sources ON public.referral_sources;
CREATE POLICY anon_read_referral_sources ON public.referral_sources FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_write_referral_sources ON public.referral_sources;
CREATE POLICY anon_write_referral_sources ON public.referral_sources FOR ALL TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS rooms_authenticated_all ON public.rooms;
CREATE POLICY rooms_authenticated_all ON public.rooms FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_schedule_blocks ON public.schedule_blocks;
CREATE POLICY allow_anon_read_schedule_blocks ON public.schedule_blocks FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS schedule_templates_delete ON public.schedule_templates;
CREATE POLICY schedule_templates_delete ON public.schedule_templates FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS schedule_templates_insert ON public.schedule_templates;
CREATE POLICY schedule_templates_insert ON public.schedule_templates FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS schedule_templates_select ON public.schedule_templates;
CREATE POLICY schedule_templates_select ON public.schedule_templates FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS schedule_templates_update ON public.schedule_templates;
CREATE POLICY schedule_templates_update ON public.schedule_templates FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_insert_scheduled_messages ON public.scheduled_messages;
CREATE POLICY allow_anon_insert_scheduled_messages ON public.scheduled_messages FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_scheduled_messages ON public.scheduled_messages;
CREATE POLICY allow_anon_read_scheduled_messages ON public.scheduled_messages FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_insert_sign_requests ON public.sign_requests;
CREATE POLICY anon_insert_sign_requests ON public.sign_requests FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS anon_select_sign_requests ON public.sign_requests;
CREATE POLICY anon_select_sign_requests ON public.sign_requests FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS anon_update_sign_requests ON public.sign_requests;
CREATE POLICY anon_update_sign_requests ON public.sign_requests FOR UPDATE TO anon USING (true);
DROP POLICY IF EXISTS allow_anon_insert_consent_log ON public.sms_consent_log;
CREATE POLICY allow_anon_insert_consent_log ON public.sms_consent_log FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS allow_anon_read_consent_log ON public.sms_consent_log;
CREATE POLICY allow_anon_read_consent_log ON public.sms_consent_log FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS tech_feedback_all ON public.tech_feedback;
CREATE POLICY tech_feedback_all ON public.tech_feedback FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS template_dependencies_delete ON public.template_dependencies;
CREATE POLICY template_dependencies_delete ON public.template_dependencies FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS template_dependencies_insert ON public.template_dependencies;
CREATE POLICY template_dependencies_insert ON public.template_dependencies FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS template_dependencies_select ON public.template_dependencies;
CREATE POLICY template_dependencies_select ON public.template_dependencies FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS template_dependencies_update ON public.template_dependencies;
CREATE POLICY template_dependencies_update ON public.template_dependencies FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS template_phases_delete ON public.template_phases;
CREATE POLICY template_phases_delete ON public.template_phases FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS template_phases_insert ON public.template_phases;
CREATE POLICY template_phases_insert ON public.template_phases FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS template_phases_select ON public.template_phases;
CREATE POLICY template_phases_select ON public.template_phases FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS template_phases_update ON public.template_phases;
CREATE POLICY template_phases_update ON public.template_phases FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS template_tasks_delete ON public.template_tasks;
CREATE POLICY template_tasks_delete ON public.template_tasks FOR DELETE TO anon, authenticated USING (true);
DROP POLICY IF EXISTS template_tasks_insert ON public.template_tasks;
CREATE POLICY template_tasks_insert ON public.template_tasks FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS template_tasks_select ON public.template_tasks;
CREATE POLICY template_tasks_select ON public.template_tasks FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS template_tasks_update ON public.template_tasks;
CREATE POLICY template_tasks_update ON public.template_tasks FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS tecr_read ON public.time_entry_change_requests;
CREATE POLICY tecr_read ON public.time_entry_change_requests FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS ted_read ON public.time_entry_deletions;
CREATE POLICY ted_read ON public.time_entry_deletions FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS anon_insert_worker_runs ON public.worker_runs;
CREATE POLICY anon_insert_worker_runs ON public.worker_runs FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS anon_read_worker_runs ON public.worker_runs;
CREATE POLICY anon_read_worker_runs ON public.worker_runs FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS anon_update_worker_runs ON public.worker_runs;
CREATE POLICY anon_update_worker_runs ON public.worker_runs FOR UPDATE TO anon, authenticated USING (true);
-- nav_permissions: restore the anon ALL policy
DROP POLICY IF EXISTS nav_permissions_anon_read ON public.nav_permissions;
CREATE POLICY nav_permissions_anon_all ON public.nav_permissions FOR ALL TO anon USING (true) WITH CHECK (true);
-- notifications_select: restore anon
ALTER POLICY notifications_select ON public.notifications TO anon, authenticated;
*/
