-- UPR security hardening — generated 2026-06-24 from live catalog.
-- Role-swap: anon/public -> authenticated, keeping USING(true)/WITH CHECK(true)
-- so logged-in employees keep byte-for-byte identical access. Workers use the
-- service role (bypass RLS); public e-sign uses SECURITY DEFINER RPCs.

BEGIN;

-- 1. Drop anon/public table policies
DROP POLICY IF EXISTS all_delete_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS all_insert_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS all_select_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS all_update_appointment_crew ON public.appointment_crew;
DROP POLICY IF EXISTS appointment_dependencies_delete ON public.appointment_dependencies;
DROP POLICY IF EXISTS appointment_dependencies_insert ON public.appointment_dependencies;
DROP POLICY IF EXISTS appointment_dependencies_select ON public.appointment_dependencies;
DROP POLICY IF EXISTS appointment_dependencies_update ON public.appointment_dependencies;
DROP POLICY IF EXISTS all_delete_appointments ON public.appointments;
DROP POLICY IF EXISTS all_insert_appointments ON public.appointments;
DROP POLICY IF EXISTS all_select_appointments ON public.appointments;
DROP POLICY IF EXISTS all_update_appointments ON public.appointments;
DROP POLICY IF EXISTS anon_delete_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS anon_insert_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS anon_select_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS anon_update_automation_rules ON public.automation_rules;
DROP POLICY IF EXISTS allow_anon_read_campaigns ON public.campaigns;
DROP POLICY IF EXISTS anon_insert_claims ON public.claims;
DROP POLICY IF EXISTS anon_read_claims ON public.claims;
DROP POLICY IF EXISTS anon_update_claims ON public.claims;
DROP POLICY IF EXISTS claims_anon_delete ON public.claims;
DROP POLICY IF EXISTS ca_delete ON public.contact_addresses;
DROP POLICY IF EXISTS ca_insert ON public.contact_addresses;
DROP POLICY IF EXISTS ca_select ON public.contact_addresses;
DROP POLICY IF EXISTS ca_update ON public.contact_addresses;
DROP POLICY IF EXISTS contact_jobs_anon_delete ON public.contact_jobs;
DROP POLICY IF EXISTS contact_jobs_anon_insert ON public.contact_jobs;
DROP POLICY IF EXISTS contact_jobs_anon_select ON public.contact_jobs;
DROP POLICY IF EXISTS contact_jobs_anon_update ON public.contact_jobs;
DROP POLICY IF EXISTS allow_anon_insert_contacts ON public.contacts;
DROP POLICY IF EXISTS allow_anon_read_contacts ON public.contacts;
DROP POLICY IF EXISTS allow_anon_update_contacts ON public.contacts;
DROP POLICY IF EXISTS allow_anon_insert_conversation_participants ON public.conversation_participants;
DROP POLICY IF EXISTS allow_anon_read_conversation_participants ON public.conversation_participants;
DROP POLICY IF EXISTS allow_anon_insert_conversations ON public.conversations;
DROP POLICY IF EXISTS allow_anon_read_conversations ON public.conversations;
DROP POLICY IF EXISTS allow_anon_update_conversations ON public.conversations;
DROP POLICY IF EXISTS demo_sheet_schemas_all ON public.demo_sheet_schemas;
DROP POLICY IF EXISTS "Own tokens or admin read" ON public.device_tokens;
DROP POLICY IF EXISTS dispatch_board_jobs_delete ON public.dispatch_board_jobs;
DROP POLICY IF EXISTS dispatch_board_jobs_insert ON public.dispatch_board_jobs;
DROP POLICY IF EXISTS dispatch_board_jobs_select ON public.dispatch_board_jobs;
DROP POLICY IF EXISTS "anon read document_templates" ON public.document_templates;
DROP POLICY IF EXISTS "anon write document_templates" ON public.document_templates;
DROP POLICY IF EXISTS anon_read_employee_page_access ON public.employee_page_access;
DROP POLICY IF EXISTS allow_anon_read_employees ON public.employees;
DROP POLICY IF EXISTS equip_authenticated_all ON public.equipment_placements;
DROP POLICY IF EXISTS anon_read_flags ON public.feature_flags;
DROP POLICY IF EXISTS anon_read_carriers ON public.insurance_carriers;
DROP POLICY IF EXISTS anon_write_insurance_carriers ON public.insurance_carriers;
DROP POLICY IF EXISTS allow_anon_read_invoices ON public.invoices;
DROP POLICY IF EXISTS anon_delete_job_documents ON public.job_documents;
DROP POLICY IF EXISTS anon_insert_job_documents ON public.job_documents;
DROP POLICY IF EXISTS anon_select_job_documents ON public.job_documents;
DROP POLICY IF EXISTS anon_update_job_documents ON public.job_documents;
DROP POLICY IF EXISTS job_documents_delete ON public.job_documents;
DROP POLICY IF EXISTS job_documents_insert ON public.job_documents;
DROP POLICY IF EXISTS job_documents_select ON public.job_documents;
DROP POLICY IF EXISTS job_documents_update ON public.job_documents;
DROP POLICY IF EXISTS anon_delete_job_notes ON public.job_notes;
DROP POLICY IF EXISTS anon_insert_job_notes ON public.job_notes;
DROP POLICY IF EXISTS anon_select_job_notes ON public.job_notes;
DROP POLICY IF EXISTS anon_update_job_notes ON public.job_notes;
DROP POLICY IF EXISTS job_number_sequences_insert ON public.job_number_sequences;
DROP POLICY IF EXISTS job_number_sequences_select ON public.job_number_sequences;
DROP POLICY IF EXISTS job_number_sequences_update ON public.job_number_sequences;
DROP POLICY IF EXISTS allow_anon_insert_phase_history ON public.job_phase_history;
DROP POLICY IF EXISTS allow_anon_read_phase_history ON public.job_phase_history;
DROP POLICY IF EXISTS allow_anon_read_phases ON public.job_phases;
DROP POLICY IF EXISTS anon_delete_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS anon_insert_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS anon_read_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS anon_update_job_schedule_phases ON public.job_schedule_phases;
DROP POLICY IF EXISTS job_schedules_delete ON public.job_schedules;
DROP POLICY IF EXISTS job_schedules_insert ON public.job_schedules;
DROP POLICY IF EXISTS job_schedules_select ON public.job_schedules;
DROP POLICY IF EXISTS job_schedules_update ON public.job_schedules;
DROP POLICY IF EXISTS anon_all ON public.job_supplements;
DROP POLICY IF EXISTS job_tasks_delete ON public.job_tasks;
DROP POLICY IF EXISTS job_tasks_insert ON public.job_tasks;
DROP POLICY IF EXISTS job_tasks_select ON public.job_tasks;
DROP POLICY IF EXISTS job_tasks_update ON public.job_tasks;
DROP POLICY IF EXISTS allow_anon_read_job_time_entries ON public.job_time_entries;
DROP POLICY IF EXISTS allow_anon_insert_jobs ON public.jobs;
DROP POLICY IF EXISTS allow_anon_read_jobs ON public.jobs;
DROP POLICY IF EXISTS allow_anon_update_jobs ON public.jobs;
DROP POLICY IF EXISTS allow_anon_read_templates ON public.message_templates;
DROP POLICY IF EXISTS allow_anon_read_messages ON public.messages;
DROP POLICY IF EXISTS allow_anon_write_messages ON public.messages;
DROP POLICY IF EXISTS moisture_authenticated_all ON public.moisture_readings;
DROP POLICY IF EXISTS nav_permissions_anon_all ON public.nav_permissions;
DROP POLICY IF EXISTS anon_insert_notification_queue ON public.notification_queue;
DROP POLICY IF EXISTS anon_select_notification_queue ON public.notification_queue;
DROP POLICY IF EXISTS anon_update_notification_queue ON public.notification_queue;
DROP POLICY IF EXISTS notifications_select ON public.notifications;
DROP POLICY IF EXISTS allow_anon_delete_payments ON public.payments;
DROP POLICY IF EXISTS allow_anon_insert_payments ON public.payments;
DROP POLICY IF EXISTS allow_anon_select_payments ON public.payments;
DROP POLICY IF EXISTS allow_anon_update_payments ON public.payments;
DROP POLICY IF EXISTS anon_read_referral_sources ON public.referral_sources;
DROP POLICY IF EXISTS anon_write_referral_sources ON public.referral_sources;
DROP POLICY IF EXISTS rooms_authenticated_all ON public.rooms;
DROP POLICY IF EXISTS allow_anon_read_schedule_blocks ON public.schedule_blocks;
DROP POLICY IF EXISTS schedule_templates_delete ON public.schedule_templates;
DROP POLICY IF EXISTS schedule_templates_insert ON public.schedule_templates;
DROP POLICY IF EXISTS schedule_templates_select ON public.schedule_templates;
DROP POLICY IF EXISTS schedule_templates_update ON public.schedule_templates;
DROP POLICY IF EXISTS allow_anon_insert_scheduled_messages ON public.scheduled_messages;
DROP POLICY IF EXISTS allow_anon_read_scheduled_messages ON public.scheduled_messages;
DROP POLICY IF EXISTS anon_insert_sign_requests ON public.sign_requests;
DROP POLICY IF EXISTS anon_select_sign_requests ON public.sign_requests;
DROP POLICY IF EXISTS anon_update_sign_requests ON public.sign_requests;
DROP POLICY IF EXISTS allow_anon_insert_consent_log ON public.sms_consent_log;
DROP POLICY IF EXISTS allow_anon_read_consent_log ON public.sms_consent_log;
DROP POLICY IF EXISTS anon_insert_system_events ON public.system_events;
DROP POLICY IF EXISTS anon_select_system_events ON public.system_events;
DROP POLICY IF EXISTS tech_feedback_all ON public.tech_feedback;
DROP POLICY IF EXISTS template_dependencies_delete ON public.template_dependencies;
DROP POLICY IF EXISTS template_dependencies_insert ON public.template_dependencies;
DROP POLICY IF EXISTS template_dependencies_select ON public.template_dependencies;
DROP POLICY IF EXISTS template_dependencies_update ON public.template_dependencies;
DROP POLICY IF EXISTS template_phases_delete ON public.template_phases;
DROP POLICY IF EXISTS template_phases_insert ON public.template_phases;
DROP POLICY IF EXISTS template_phases_select ON public.template_phases;
DROP POLICY IF EXISTS template_phases_update ON public.template_phases;
DROP POLICY IF EXISTS template_tasks_delete ON public.template_tasks;
DROP POLICY IF EXISTS template_tasks_insert ON public.template_tasks;
DROP POLICY IF EXISTS template_tasks_select ON public.template_tasks;
DROP POLICY IF EXISTS template_tasks_update ON public.template_tasks;
DROP POLICY IF EXISTS anon_insert_worker_runs ON public.worker_runs;
DROP POLICY IF EXISTS anon_read_worker_runs ON public.worker_runs;
DROP POLICY IF EXISTS anon_update_worker_runs ON public.worker_runs;

-- 2. Recreate each as authenticated (identical USING/WITH CHECK)
CREATE POLICY all_delete_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY all_insert_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY all_select_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY all_update_appointment_crew ON public.appointment_crew AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY appointment_dependencies_delete ON public.appointment_dependencies AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY appointment_dependencies_insert ON public.appointment_dependencies AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY appointment_dependencies_select ON public.appointment_dependencies AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY appointment_dependencies_update ON public.appointment_dependencies AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY all_delete_appointments ON public.appointments AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY all_insert_appointments ON public.appointments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY all_select_appointments ON public.appointments AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY all_update_appointments ON public.appointments AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_delete_automation_rules ON public.automation_rules AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY anon_insert_automation_rules ON public.automation_rules AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_select_automation_rules ON public.automation_rules AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_automation_rules ON public.automation_rules AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_campaigns ON public.campaigns AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_insert_claims ON public.claims AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_read_claims ON public.claims AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_claims ON public.claims AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY claims_anon_delete ON public.claims AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY ca_delete ON public.contact_addresses AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY ca_insert ON public.contact_addresses AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY ca_select ON public.contact_addresses AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY ca_update ON public.contact_addresses AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY contact_jobs_anon_delete ON public.contact_jobs AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY contact_jobs_anon_insert ON public.contact_jobs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY contact_jobs_anon_select ON public.contact_jobs AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY contact_jobs_anon_update ON public.contact_jobs AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY allow_anon_insert_contacts ON public.contacts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_contacts ON public.contacts AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_update_contacts ON public.contacts AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_insert_conversation_participants ON public.conversation_participants AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_conversation_participants ON public.conversation_participants AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_insert_conversations ON public.conversations AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_conversations ON public.conversations AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_update_conversations ON public.conversations AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY demo_sheet_schemas_all ON public.demo_sheet_schemas AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Own tokens or admin read" ON public.device_tokens AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY dispatch_board_jobs_delete ON public.dispatch_board_jobs AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY dispatch_board_jobs_insert ON public.dispatch_board_jobs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY dispatch_board_jobs_select ON public.dispatch_board_jobs AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "anon read document_templates" ON public.document_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "anon write document_templates" ON public.document_templates AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_read_employee_page_access ON public.employee_page_access AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_read_employees ON public.employees AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY equip_authenticated_all ON public.equipment_placements AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_read_flags ON public.feature_flags AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_read_carriers ON public.insurance_carriers AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_write_insurance_carriers ON public.insurance_carriers AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_invoices ON public.invoices AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_delete_job_documents ON public.job_documents AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY anon_insert_job_documents ON public.job_documents AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_select_job_documents ON public.job_documents AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_job_documents ON public.job_documents AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY job_documents_delete ON public.job_documents AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY job_documents_insert ON public.job_documents AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY job_documents_select ON public.job_documents AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY job_documents_update ON public.job_documents AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY anon_delete_job_notes ON public.job_notes AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY anon_insert_job_notes ON public.job_notes AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_select_job_notes ON public.job_notes AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_job_notes ON public.job_notes AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY job_number_sequences_insert ON public.job_number_sequences AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY job_number_sequences_select ON public.job_number_sequences AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY job_number_sequences_update ON public.job_number_sequences AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY allow_anon_insert_phase_history ON public.job_phase_history AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_phase_history ON public.job_phase_history AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_read_phases ON public.job_phases AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_delete_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY anon_insert_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_read_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_job_schedule_phases ON public.job_schedule_phases AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY job_schedules_delete ON public.job_schedules AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY job_schedules_insert ON public.job_schedules AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY job_schedules_select ON public.job_schedules AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY job_schedules_update ON public.job_schedules AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.job_supplements AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY job_tasks_delete ON public.job_tasks AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY job_tasks_insert ON public.job_tasks AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY job_tasks_select ON public.job_tasks AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY job_tasks_update ON public.job_tasks AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_job_time_entries ON public.job_time_entries AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_insert_jobs ON public.jobs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_jobs ON public.jobs AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_update_jobs ON public.jobs AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_templates ON public.message_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_read_messages ON public.messages AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_write_messages ON public.messages AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY moisture_authenticated_all ON public.moisture_readings AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY nav_permissions_anon_all ON public.nav_permissions AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_insert_notification_queue ON public.notification_queue AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_select_notification_queue ON public.notification_queue AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_notification_queue ON public.notification_queue AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY notifications_select ON public.notifications AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_delete_payments ON public.payments AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY allow_anon_insert_payments ON public.payments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_select_payments ON public.payments AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY allow_anon_update_payments ON public.payments AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_read_referral_sources ON public.referral_sources AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_write_referral_sources ON public.referral_sources AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY rooms_authenticated_all ON public.rooms AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_read_schedule_blocks ON public.schedule_blocks AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY schedule_templates_delete ON public.schedule_templates AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY schedule_templates_insert ON public.schedule_templates AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY schedule_templates_select ON public.schedule_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY schedule_templates_update ON public.schedule_templates AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY allow_anon_insert_scheduled_messages ON public.scheduled_messages AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_scheduled_messages ON public.scheduled_messages AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_insert_sign_requests ON public.sign_requests AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_select_sign_requests ON public.sign_requests AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_sign_requests ON public.sign_requests AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY allow_anon_insert_consent_log ON public.sms_consent_log AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY allow_anon_read_consent_log ON public.sms_consent_log AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_insert_system_events ON public.system_events AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_select_system_events ON public.system_events AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY tech_feedback_all ON public.tech_feedback AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY template_dependencies_delete ON public.template_dependencies AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY template_dependencies_insert ON public.template_dependencies AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY template_dependencies_select ON public.template_dependencies AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY template_dependencies_update ON public.template_dependencies AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY template_phases_delete ON public.template_phases AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY template_phases_insert ON public.template_phases AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY template_phases_select ON public.template_phases AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY template_phases_update ON public.template_phases AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY template_tasks_delete ON public.template_tasks AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY template_tasks_insert ON public.template_tasks AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY template_tasks_select ON public.template_tasks AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY template_tasks_update ON public.template_tasks AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY anon_insert_worker_runs ON public.worker_runs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY anon_read_worker_runs ON public.worker_runs AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY anon_update_worker_runs ON public.worker_runs AS PERMISSIVE FOR UPDATE TO authenticated USING (true);

-- 3. Definer-rights views: keep authenticated read, remove anon
GRANT SELECT ON public.active_jobs, public.billing_overview, public.demo_sheets, public.job_equipment_costs, public.todays_schedule TO authenticated;
REVOKE ALL ON public.active_jobs, public.billing_overview, public.demo_sheets, public.job_equipment_costs, public.todays_schedule FROM anon;

-- 4. Defense-in-depth: drop residual anon TABLE privileges (RLS already denies;
--    closes any RLS-off gap + the views). Anon EXECUTE on e-sign RPCs untouched.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;

COMMIT;
